{
  "hash": "5ea6fd1e8566eca0c7b44969bc258cff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Philadelphia Housing Model - Technical Appendix\"\nauthor: \"Jinyang Xu, Xinyuan Cui, Yuqing Yang\"\nformat: \n  html:\n    code-fold: show\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n## Phase 1: Data Preparation\n### Complete data cleaning code\n\n***Load necessary libraries***\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(tidycensus)\nlibrary(tigris)\noptions(tigris_use_cache = TRUE, tigris_class = \"sf\")\nlibrary(MASS)\nlibrary(dplyr)\nlibrary(scales)\nlibrary(ggplot2)\nlibrary(caret)\nlibrary(nngeo)\nlibrary(car)\nlibrary(knitr)\nlibrary(readr)\nlibrary(patchwork)\n# Add this near the top of your .qmd after loading libraries\noptions(tigris_use_cache = TRUE)\noptions(tigris_progress = FALSE)  \n```\n:::\n\n\n**1.1 Load and clean Philadelphia sales data:**\n\n- 1.1.1 Load data\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nopa <- read_csv(\"opa_properties_public1.csv\")\n```\n:::\n\n\n- 1.1.2 Filter to residential properties, 2023-2024 sales\n\n::: {.cell}\n\n```{.r .cell-code}\n# data in 2022 will be used as predictor, so keep them as well.\nopa_clean <- opa %>%\n  mutate(sale_date = as.Date(sale_date)) %>%\n  filter(sale_date >= \"2022-01-01\" & sale_date <= \"2024-12-31\",\n  category_code == \"1\"  # 1 indicates single family\n  )\n\n# record the amount of data we will focus on\nopa_clean2 <- opa %>%\n  mutate(sale_date = as.Date(sale_date)) %>%\n  filter(sale_date >= \"2023-01-01\" & sale_date <= \"2024-12-31\",\n  category_code == \"1\"  # 1 indicates single family\n  )\n\n# Select relevant variables \nopa_var <- opa_clean %>%\n  dplyr::select(\n    sale_date, sale_price, market_value, building_code_description,\n    total_livable_area, number_of_bedrooms, number_of_bathrooms,\n    number_stories, garage_spaces, central_air, quality_grade,\n    interior_condition, exterior_condition, year_built, \n    off_street_open, zip_code, census_tract, zoning, owner_1,\n    category_code_description, shape, fireplaces\n  )\n```\n:::\n\n\n- 1.1.3 Remove obvious errors & Handle missing values\n\n::: {.cell}\n\n```{.r .cell-code}\n# ! check before remove NA value\n\ncat(\"<small>\n💡 Data Cleaning Notes:<br>\n- Remove NA only if missing count is small.<br>\n- If many are missing, retain them and transform NA into a meaningful category.<br>\n- Always record how missing values were handled.\n</small>\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<small>\n💡 Data Cleaning Notes:<br>\n- Remove NA only if missing count is small.<br>\n- If many are missing, retain them and transform NA into a meaningful category.<br>\n- Always record how missing values were handled.\n</small>\n```\n\n\n:::\n\n```{.r .cell-code}\n#remove errors and drop rows with small NA counts in specific columns\nopa_var <- opa_var %>% \n  distinct() %>%  #Remove duplicate lines\n  filter(\n    !is.na(total_livable_area) & total_livable_area > 0,\n    !is.na(year_built) & year_built > 0 & year_built < 2025,\n    !is.na(number_of_bathrooms),\n    !is.na(fireplaces),\n    !is.na(interior_condition),\n    garage_spaces<30\n  )   \n```\n:::\n\n\n- 1.1.4 Other cleaning decisions\n\n::: {.cell}\n\n```{.r .cell-code}\n#numeric quality_grade\nvalid_grades <- c(\"A+\", \"A\", \"A-\", \n                  \"B+\", \"B\", \"B-\", \n                  \"C+\", \"C\", \"C-\", \n                  \"D+\", \"D\", \"D-\", \n                  \"E+\", \"E\", \"E-\")\n\nopa_var <- opa_var %>%\n  filter(quality_grade %in% valid_grades) %>%\n  mutate(\n    quality_grade = factor(quality_grade, levels = valid_grades, ordered = TRUE),\n    quality_grade_num = rev(seq_along(valid_grades))[as.numeric(quality_grade)]\n  )\n\n#central_air (keep and transform the large NA values)\nopa_var <- opa_var %>%\n  mutate(\n    central_air_dummy = case_when(\n      central_air %in% c(1, \"Y\", \"y\") ~ 1,\n      central_air %in% c(0, \"N\", \"n\") ~ 0,\n      TRUE ~ NA_real_\n    ),\n    central_air_missing = if_else(is.na(central_air), 1, 0),\n    central_air_dummy = if_else(is.na(central_air_dummy), 0, central_air_dummy)\n  )\n\n#house age\nopa_var <- opa_var %>%\n  mutate(\n    house_age = 2025 - year_built\n  )\n```\n:::\n\n\n- 1.1.5 Explore structural data biases and identify non-market transactions\n\n::: {.cell}\n\n```{.r .cell-code}\n# check the relation of Sale Price ~ Market Value\noptions(scipen = 999)\nplot(opa_var$sale_price, opa_var$market_value,\n     xlab = \"Sale Price\", ylab = \"Market Price\",\n     main = \" Market Value (Predicted)  vs  Sale Price (Actual)\",\n     pch = 19, col = rgb(0.2,0.4,0.6,0.4))\nabline(0,1,col=\"red\",lwd=2)\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a new column to record the identified non-market transactions\nopa_var <- opa_var %>%\n  mutate(\n    non_market = \n      (((sale_price < 0.10*market_value) | sale_price < 2000) | (sale_price> 5*market_value))\n  )\n```\n:::\n\n\n**Interpretation**:\n- The goal of this model is to predict typical, market-driven sale prices. The provided scatter plot of Market Value (Predicted) vs. Sale Price (Actual) is an essential diagnostic tool for assessing data quality.\n- The red line on the plot represents a perfect 1-to-1 relationship (Y=X), where the property's actual sale price is exactly equal to its predicted market value. While most data points cluster tightly around this line—indicating the \"Market Value\" is a strong predictor—the plot clearly reveals two distinct types of extreme outliers that do not represent typical market transactions.\n1. Removing Non-Market Sales (The Sale Price < 0.05 * Market Value Rule)\n  - There is a dense cluster of points stacked vertically along the y-axis, where Sale Price (X) is near zero, but Market Value (Y) is high (e.g., $1M, $2M, even $4M). These points represent transactions where a property was \"sold\" for a price that is a tiny fraction of its assessed worth (e.g., a $2,000,000 house sold for $50,000).\n  - These are non-arm's-length transactions, not true market sales. Examples include sales between family members, inheritance transfers, or other legal transactions where the price does not reflect the market.\n2. Removing Anomalous High Sales (The Sale Price > 5 * Market Value Rule)\n  - There are several data points scattered far to the right and bottom of the plot, far below the red Y=X line. These points represent properties where the Sale Price (X) was massively higher than its Market Value (Y). For example, a property with an assessed value of $500,000 (Y) selling for $4,000,000 (X).\n  - These are also not typical sales. They could represent (a) data entry errors, (b) sales where the \"Market Value\" figure is obsolete (e.g., a run-down property sold for land value/development potential), or (c) properties that underwent major renovations not yet captured in the assessed value.\n- Retaining these two groups of outliers would severely skew the model's coefficients and reduce its predictive accuracy for the vast majority of normal, market-based transactions. This filtering rule is a necessary step to clean the data, ensure the model learns from valid transactions, and improve its overall reliability.\n\n- 1.1.6 enhance the sales data\n\nWe have 8000+ non market transactions, that is 1/4 of the total sales data!\nThat's too big to let go, The model that we want to generate will become much more stable if we can make use of them.\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter the REAL MARKET data in the time period we need\nopa_selected <- opa_var %>% \n  filter(\n    non_market==0,\n    sale_date >= \"2023-01-01\" & sale_date <= \"2024-12-31\"\n  )   \n\n#filter the NON MARKET data in the time period we need\nopa_non_market <- opa_var %>%\n  filter(\n    non_market ==1,\n    sale_date >= \"2023-01-01\" & sale_date <= \"2024-12-31\"\n    )\n\nopa_selected2 <- opa_var\nopa_bonus <- opa_var \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#try to find the relationship between market_value and sale_price\noptions(scipen = 999)\nplot(opa_selected$sale_price, opa_selected$market_value,\n     xlab = \"Sale Price\", ylab = \"Market Price\",\n     main = \" Market Value vs  Sale Price (cleaned)\",\n     pch = 19, col = rgb(0.2,0.4,0.6,0.4))\nabline(0,1,col=\"red\",lwd=2)\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# That's quite linear, let's try to build a simple OLS model\nopa_mdata <- opa_bonus %>%\n  filter(\n    non_market == 0\n    )\n\nmodel_non <- lm(sale_price ~ market_value, data = opa_mdata)\nsummary(model_non)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ market_value, data = opa_mdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1432832   -35207    -1669    30014  1975714 \n\nCoefficients:\n                 Estimate   Std. Error t value            Pr(>|t|)    \n(Intercept)  -9189.286424   663.771782  -13.84 <0.0000000000000002 ***\nmarket_value     1.027924     0.001773  579.62 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 86310 on 40927 degrees of freedom\nMultiple R-squared:  0.8914,\tAdjusted R-squared:  0.8914 \nF-statistic: 3.36e+05 on 1 and 40927 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n\n```{.r .cell-code}\npred <- predict(model_non, newdata = opa_mdata)\nresid <- opa_mdata$sale_price - pred\n\n# RMSE\nrmse_value <- sqrt(mean(resid^2, na.rm = TRUE))\nrmse_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 86311.29\n```\n\n\n:::\n:::\n\nThe results demonstrate a very strong linear relationship between sale_price and market_value.\nThe market_value variable in the dataset effectively predicts the sale_price.\nTherefore, we can leverage this relationship to estimate the normal market prices for non-market transactions.\nWe record these estimated values as sale_price_predicted.\nBy doing this, we enhance our data!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#bring data back\nopa_non_market$sale_price_predicted <- predict(model_non, newdata = opa_non_market)\n\n#join back to the main data\nopa_selected <- opa_selected %>%\n  mutate(sale_price_predicted= sale_price)\n\nset.seed(123)\nopa_bind <- bind_rows(opa_selected, opa_non_market) %>%\n  slice_sample(prop = 1)\n```\n:::\n\n\n\n**1.2 Load and clean secondary dataset:**\n\n- 1.2.1 Census data (tidycensus):\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to sf object \nopa_bind <- st_as_sf(opa_bind, wkt = \"shape\", crs = 2272) %>%\n  st_transform(4326)\nopa_sf<- opa_bind\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Census data for Philadelphia tracts\nphilly_census <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    \n    ba_degree = \"B15003_022\",\n    total_edu = \"B15003_001\",\n    \n    median_income = \"B19013_001\",\n   \n    labor_force = \"B23025_003\",\n    unemployed = \"B23025_005\",\n    \n    total_housing = \"B25002_001\",\n    vacant_housing = \"B25002_003\"\n  ),\n  year = 2023,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  geometry = TRUE\n) %>%\n  dplyr::select(GEOID, variable, estimate, geometry) %>%   \n  tidyr::pivot_wider(names_from = variable, values_from = estimate) %>%\n  dplyr::mutate(\n    ba_rate = 100 * ba_degree / total_edu,\n    unemployment_rate = 100 * unemployed / labor_force,\n    vacancy_rate = 100 * vacant_housing / total_housing\n  ) %>%\n  st_transform(st_crs(opa_sf))\n\n# Spatial join of OPA data with Census data\nopa_census <- st_join(opa_sf, philly_census, join = st_within) %>%\n  filter(!is.na(median_income))\n```\n:::\n\n\n- 1.2.2 Spatial amenities (OpenDataPhilly)\n\n::: {.cell}\n\n```{.r .cell-code}\n#load crime,poi,transit,hospital\nopa_census <- st_transform(opa_census, 3857)\n\ncrime <- read_csv(\"crime_sel.csv\") %>% \n  filter(!is.na(lat) & !is.na(lng)) \ncrime_sf <- st_as_sf(crime, coords = c(\"lng\", \"lat\"), crs = 4326) %>%\n  st_transform(st_crs(opa_census)) \n\npoi_sf <- st_read(\"data/gis_osm_pois_a_free_1.shp\", quiet = TRUE) %>%\n  st_transform(st_crs(opa_census)) \n\nTransit <- read_csv(\"Transit.csv\")\ntransit_sf <- st_as_sf(Transit, coords = c(\"Lon\", \"Lat\"), crs = 4326) %>%\n  st_transform(st_crs(opa_census))\n\nhospital_sf <- st_read(\"hospitals.geojson\", quiet = TRUE) %>%\n  st_transform(st_crs(opa_census))\n```\n:::\n\n\n**1.3 Summary tables showing before/after dimensions**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Original data dimensions\nopa_dims <- tibble(\n  dataset = \"raw CSV\",\n  rows = nrow(opa),\n  columns = ncol(opa)\n)\n\n# cleaned data dimensions\nopa_filter_dims <- tibble(\n  dataset = \"after fixed criteria\",\n  rows = nrow(opa_clean2),\n  columns = ncol(opa_clean2)\n)\n\nopa_selected_dims <- tibble(\n  dataset = \"after cleaned\",\n  rows = nrow(opa_bind),\n  columns = ncol(opa_bind)\n)\n# data dimensions (within census tracts)\nopa_census_dims <- tibble(\n  dataset = \"after census joined\",\n  rows = nrow(opa_census),\n  columns = ncol(opa_census)\n)\n\n# create summary table\nsummary_table <- bind_rows(opa_dims, opa_filter_dims,opa_selected_dims, opa_census_dims)\nlibrary(knitr)\nsummary_table %>%\n  kable(caption = \"Summary of OPA data before and after cleaning\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of OPA data before and after cleaning\n\n|dataset              |   rows| columns|\n|:--------------------|------:|-------:|\n|raw CSV              | 153267|      79|\n|after fixed criteria |  34559|      79|\n|after cleaned        |  31968|      28|\n|after census joined  |  31613|      40|\n\n\n:::\n:::\n\n\n\n**Principles of Data Processing**\n\n- opa Data  \n  - Filter `sale_date` between `2023-01-01` and `2024-12-31`.  \n  - Keep only residential properties (`category_code == 1`).  \n  - Remove records with missing values in `total_livable_area`, `sale_price`, or `number_of_bathrooms`.  \n  - Filter records `year_built > 0` .\n  \n- Census data  \n  - Load data including `total_pop`, `ba_degree`, `total_edu`, `median_income`, `labor_force`, `unemployed`, `total_housing`, `vacant_housing`.\n  - Transform to spatial format and remove records with missing values.\n  \n- Spatial amenities\n  - Load datasets *Transit*, *crime*, *POIs*, *Hospitals*.\n  - Transform to spatial format and remove records with missing values.\n\n**Interpretation**: \nThe selected variables can be grouped into several meaningful categories that are theoretically and empirically linked to housing prices:  \n- Neighborhood Safety:\n  - Crime data: Areas with lower crime rates are generally more desirable, leading to higher property values. Including crime incidents helps capture the effect of public safety on housing prices.\n- Accessibility and Transportation:\n  - Transit points: Proximity to public transportation (e.g., bus stops, subway stations) increases accessibility and convenience, which is often capitalized into higher home values.\n  - Points of Interest (POIs): Nearby amenities such as shops, restaurants, and parks improve quality of life and can positively influence housing prices.\n- Healthcare Access:\n  - Hospitals: Easy access to healthcare facilities is a valued neighborhood characteristic, especially for families and older residents, and can contribute to higher property values.\n- Socioeconomic and Demographic Context (from Census data):\n  - Total population: Indicates population density, which can affect demand for housing.\n  - Educational attainment (e.g., % with BA degree): Higher education levels are often correlated with higher income and neighborhood desirability.\n  - Median income: Directly influences purchasing power and demand for housing in an area.\n  - Employment status (labor force and unemployment): Reflects economic stability and local job market health, which affect housing demand.\n  - Housing market conditions (total and vacant housing): Vacancy rates can signal neighborhood decline or oversupply, both of which impact prices.\n- Together, these variables provide a multidimensional view of a neighborhood’s appeal, safety, convenience, and economic health—all key determinants of housing prices.\n\n---\n\n## Phase 2: Feature Engineering \n\n**2.1 Buffer-based features**:\n\n- 2.1.1 neighborhood avg sale price in the past year\n\n::: {.cell}\n\n```{.r .cell-code}\n#filter the past sales data\n\nopa_census <- opa_census %>%\n  mutate(sale_id = row_number())\n\n\n\nopa_past <- opa_var %>% \n  filter(\n    non_market==0,\n    sale_date >= \"2022-01-01\" & sale_date <= \"2022-12-31\"\n  ) \n\nopa_past <- opa_past %>%\n  mutate(sale_id2 = row_number())\n\nopa_past <- st_as_sf(opa_past, wkt = \"shape\", crs = 2272) %>%\n  st_transform(3857)\n\nopa_census <- st_transform(opa_census, 3857)\nopa_past   <- st_transform(opa_past, 3857)\n\nopa_census_buffer <- st_buffer(opa_census, 300)\ndrop_cols <- names(opa_census_buffer) %in% c(\"sale_price\", \"total_livable_area\",\n                                             \"sale_price.y\", \"total_livable_area.y\")\nopa_census_buffer <- opa_census_buffer[ , !drop_cols, drop = FALSE]\n\njoin_result <- st_join(\n  opa_census_buffer,\n  opa_past,\n  join = st_intersects,\n  left = TRUE\n)\n\n\njoin_result <- st_join(\n  opa_census_buffer,\n  opa_past,\n  join = st_intersects,\n  left = TRUE\n)\njoin_dedup <- join_result %>%\n  st_drop_geometry() %>%\n  distinct(sale_id, sale_id2, .keep_all = TRUE)\n\nopa_summary <- join_dedup %>%\n  group_by(sale_id) %>%\n  summarise(\n    past_count = sum(!is.na(sale_id2)),\n    avg_past_price_density = ifelse(\n      sum(!is.na(total_livable_area)) == 0, NA_real_,\n      sum(sale_price, na.rm = TRUE) / sum(total_livable_area, na.rm = TRUE)\n    ),\n    .groups = \"drop\"\n  )\nopa_census <- opa_census %>%\n  left_join(opa_summary, by = \"sale_id\")\n```\n:::\n\n\n- 2.1.2 crime numbers \n\n::: {.cell}\n\n```{.r .cell-code}\nradius_cri <- 250 \n\nopa_census$crime_count <- lengths(st_is_within_distance(opa_census, crime_sf, dist = radius_cri)) \n```\n:::\n\n\n- 2.1.3 POI numbers \n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census_m <- st_transform(opa_census, 3857)\npoi_sf_m     <- st_transform(poi_sf, 3857)\n\n\nradius_poi <- 400\nopa_census_buffer <- st_buffer(opa_census_m, radius_poi)\n\njoin_result <- st_join(opa_census_buffer, poi_sf_m, join = st_intersects, left = TRUE)\n\npoi_summary <- join_result %>%\n  st_drop_geometry() %>%\n  group_by(sale_id) %>%\n  summarise(poi_count = sum(!is.na(osm_id)))  \n\nopa_census <- opa_census_m %>%\n  left_join(poi_summary, by = \"sale_id\")\n```\n:::\n\n\n- 2.1.4 Transit numbers\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census_m <- st_transform(opa_census, 3857)\ntransit_sf_m <- st_transform(transit_sf, 3857)\n\nradius_ts <- 400\nopa_census_buffer <- st_buffer(opa_census_m, radius_ts)\n\njoin_result <- st_join(opa_census_buffer, transit_sf_m, join = st_intersects, left = TRUE)\n\ntransit_summary <- join_result %>%\n  st_drop_geometry() %>%\n  group_by(sale_id) %>%\n  summarise(transit_count = sum(!is.na(FID)))  \n\nopa_census <- opa_census_m %>%\n  left_join(transit_summary, by = \"sale_id\")\n```\n:::\n\n\n\n**2.2 k-Nearest Neighbor features**:\n\n- 2.2.1 Hospitals (KNN-3)\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_hospital_index <- st_nn(\n  opa_census,\n  hospital_sf,\n  k = 3,            \n  returnDist = TRUE \n)\n\nopa_census$nearest_hospital_knn3 <- sapply(nearest_hospital_index$dist, mean)\n```\n:::\n\n\n\n**2.3 Weights**:\n\n::: {.cell}\n\n```{.r .cell-code}\n# add different weights to actual and non market transactions\n\nopa_census_all <- opa_census\n\nnon_market_share<- mean(opa_census_all$non_market == 1, na.rm = TRUE)\nnon_market_share\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.261791\n```\n\n\n:::\n\n```{.r .cell-code}\nopa_census_all <- opa_census %>%\n  mutate(weight_mix = ifelse(non_market == 1, non_market_share, 1))\n```\n:::\n\n**2.4 Transformation**:\n\n::: {.cell}\n\n```{.r .cell-code}\n#standardize houseage and median income\nmean_age_all <- mean(opa_census_all$house_age, na.rm = TRUE)\nmean_income_log <- mean(log(opa_census_all$median_income), na.rm = TRUE)\n\n# centralize\nopa_census_all <- opa_census_all %>%\n  mutate(\n    house_age_c  = house_age - mean_age_all,\n    house_age_c2 = house_age_c^2,\n    income_log   = log(median_income),\n    income_scaled = income_log - mean_income_log\n  )\n\nopa_census_2<- opa_census_all %>%\n  filter(\n    non_market==0\n  )\n```\n:::\n\n\n\n---\n\n\n## Phase 3: Exploratory Data Analysis\n\n### 3.1 Distribution of sale prices (histogram)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(opa_census_all, aes(x = sale_price_predicted)) +\n  geom_histogram(\n    bins = 50,                 # 调整分箱数量\n    fill = \"#6A1B9A\",          # 柱子颜色\n    color = \"white\",           # 边框颜色\n    alpha = 0.8                # 透明度\n  ) +\n  scale_x_continuous(labels = scales::dollar_format()) +\n  theme_minimal(base_size = 12) +\n  labs(\n    title = \"Distribution of  Sale Prices\",\n    x = \"Predicted Sale Price (USD)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(opa_census_all, aes(x = log(sale_price_predicted))) +\n  geom_histogram(\n    bins = 50,                 # 调整分箱数量\n    fill = \"#6A1B9A\",          # 柱子颜色\n    color = \"white\",           # 边框颜色\n    alpha = 0.8                # 透明度\n  ) +\n  scale_x_continuous() +\n  theme_minimal(base_size = 12) +\n  labs(\n    title = \"Distribution of  Log(Sale Prices)\",\n    x = \"Log(Predicted Sale Price) \",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n**Key Findings:** \n- **Highly Right-Skewed:** The bulk of the distribution is concentrated on the left side (low price range), while the right tail is very long, extending towards higher prices. This means that the majority of houses have lower prices, and very expensive houses are very few in number.  \n- **Concentration and Outliers:** The count of houses in each bin drops rapidly as the price increases. The number of houses above $2,500,000 is very small, indicating the presence of extreme high-price outliers.  \n- **Preprocessing Requirement:** This distribution strongly suggests that before building a house price prediction model, the Sale Price variable will need a transformation, most commonly a log transformation, to make the distribution more closely resemble a normal distribution.\n\n### 3.2 Spatial distribution of sale prices (map)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census_all <- opa_census_all %>%\n  mutate(price_quartile = ntile(sale_price_predicted, 4))\n\nggplot() +\n  geom_sf(data = philly_census, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = opa_census_all, aes(color = factor(price_quartile)), size = 0.5, alpha = 0.7) +\n  scale_color_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    labels = c(\"0%-25%\", \"25%-50%\", \"50%-75%\", \"75%-100%\")\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Housing Sales Price in Philadelphia (2023–2024)\",\n    color = \"Sale Price Quartile\"\n  )  +\n  guides(color = guide_legend(override.aes = list(size = 3)))\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n**Key Findings:**  \n- **Spatial Concentration of Housing Prices:** Highest Prices are clearly concentrated in the Center City/Downtown area of Philadelphia and its immediate surroundings, which indicates that the most expensive property transactions occur in the high-value areas of and around the city center.  \n- **Discontinuous Price Transitions:** Housing prices do not exhibit smooth gradients across the city; instead, they show abrupt changes between different price quartiles, forming distinct spatial clusters. This suggests that price variations are influenced by fixed boundaries such as neighborhoods, infrastructure, or socio-economic factors, rather than continuous spatial diffusion.\n- **Peripheral Price Patterns:** Lower-price quartiles (0%-25% and 25%-50%) are predominantly located in the outer regions of the city, particularly in the northern and southern peripheries, indicating a clear core-periphery divide in housing values.\n\n\n### 3.3 Price vs. structural features (scatter plots)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census_plot <- opa_census_all %>%\n  mutate(log_sale_price = log(sale_price_predicted))\n\n# 1️⃣ total_livable_area\np1 <- ggplot(opa_census_plot, aes(x = log(total_livable_area), y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(\n    title = \"Log(Sale Price) vs. Log(Livable Area)\",\n    x = \"Log(Total Livable Area)\",\n    y = \"Log(Sale Price)\"\n  ) +\n  theme_minimal(base_size = 10)\n\n# 2️⃣ number_of_bathrooms\np2 <- ggplot(opa_census_plot, aes(x = number_of_bathrooms, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(\n    title = \"Log(Sale Price) vs. Bathrooms\",\n    x = \"Number of Bathrooms\",  \n    y = \"\"\n  ) +\n  theme_minimal(base_size = 10)\n\n# 3️⃣ interior_condition\np3 <- ggplot(opa_census_plot, aes(x = interior_condition, y = log_sale_price)) +\n  geom_jitter(alpha = 0.5, color = \"#6A1B9A\", width = 0.2, height = 0) +  \n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(\n    title = \"Log(Sale Price) vs. Interior Condition\",\n    x = \"Interior Condition\",\n    y = \"Log(Sale Price)\"\n  ) +\n  theme_minimal(base_size = 10)\n\n# 4️⃣ house_age\np4 <- ggplot(opa_census_plot, aes(x = house_age^2, y = log_sale_price)) + \n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(\n    title = \"Log(Sale Price) vs. House Age²\",\n    x = \"House Age² (2025 - Year Built)²\",\n    y = \"\"\n  ) +\n  theme_minimal(base_size = 10)\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/3.3.1 log(sale_price_predicted) vs total_livable_area-1.png){width=672}\n:::\n:::\n\n\n\nquarto check\n**Key Findings:**  \n- **Strong Positive Correlation with Size and Bathrooms:** There is a clear positive linear relationship between the log of sale price and both the log of total livable area and the number of bathrooms. This indicates that larger properties and those with more bathrooms command significantly higher market prices.\n- **Non-Linear Relationship with Interior Condition:** While a general positive trend exists, the relationship between log sale price and interior condition rating is not perfectly linear. The data dispersion suggests that the effect of interior condition on price may be subject to diminishing marginal returns or other non-linear dynamics.\n- **Negative Correlation with House Age Squared:** A significant negative relationship is observed between log sale price and the squared term of house age. This indicates that property values depreciate as homes get older, and this depreciation effect may accelerate over time, reflecting a non-linear aging effect on housing value.\n\n\n### 3.4 Price vs. spatial & Social features (scatter plots)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census_plot <- opa_census_all %>%\n  mutate(\n    log_sale_price = log(sale_price_predicted),\n    sqrt_crime_count = sqrt(crime_count)\n  )\n\np1 <- ggplot(opa_census_plot, aes(x = ba_rate, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  scale_x_continuous(labels = percent_format(accuracy = 1)) +\n  labs(title = \"Log(Sale Price) vs. BA Rate\",\n       x = \"Bachelor's Degree Rate\", y = \"Log(Sale Price)\") +\n  theme_minimal(base_size = 10)\n\np2 <- ggplot(opa_census_plot, aes(x = unemployment_rate, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  scale_x_continuous(labels = percent_format(accuracy = 1)) +\n  labs(title = \"Log(Sale Price) vs. Unemployment Rate\",\n       x = \"Unemployment Rate\", y = \"\") +\n  theme_minimal(base_size = 10)\n\np3 <- ggplot(opa_census_plot, aes(x = median_income, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  scale_x_continuous(labels = dollar_format()) +\n  labs(title = \"Log(Sale Price) vs. Median Income\",\n       x = \"Median Household Income (USD)\", y = \"Log(Sale Price)\") +\n  theme_minimal(base_size = 10)\n\np4 <- ggplot(opa_census_plot, aes(x = avg_past_price_density, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(title = \"Log(Sale Price) vs. Past Price Density\",\n       x = \"Average Past Price Density\", y = \"\") +\n  theme_minimal(base_size = 10)\n\np5 <- ggplot(opa_census_plot, aes(x = sqrt_crime_count, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(title = \"Log(Sale Price) vs. √(Crime Count)\",\n       x = \"Square Root of Crime Count\", y = \"Log(Sale Price)\") +\n  theme_minimal(base_size = 10)\n\np6 <- ggplot(opa_census_plot, aes(x = transit_count, y = log_sale_price)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +\n  labs(title = \"Log(Sale Price) vs. Transit Count\",\n       x = \"Number of Transit Stops Nearby\", y = \"\") +\n  theme_minimal(base_size = 10)\n\n(p1 | p2 | p3) / (p4 | p5 | p6)\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/3.4.1 log(sale_price_predicted) vs crime_count-1.png){width=672}\n:::\n:::\n\n\n\n**Key Findings:**  \n- **Strong Socioeconomic Influence:** Housing prices show clear positive correlations with key socioeconomic indicators. Both bachelor's degree rate and median household income exhibit strong positive relationships with sale prices, indicating that neighborhoods with higher educational attainment and income levels command substantially higher property values.\n- **Negative Impact of Crime and Unemployment:** There are evident negative relationships between housing prices and both crime levels (measured by square root of crime count) and unemployment rates. This demonstrates that public safety and local economic vitality are significant determinants of property values in Philadelphia.\n- **Positive Effects of Historical Prices and Transit Access:** Sale prices maintain a positive relationship with both historical price density and accessibility to public transportation. This suggests that areas with established high-value characteristics and better transit infrastructure maintain their premium in the housing market, reflecting path dependence in neighborhood valuation and the value of transportation accessibility.\n\n\n### Other visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_price <- opa_census_all %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(avg_past_price_density = mean(avg_past_price_density, na.rm = TRUE))\n\ntract_map <- philly_census %>%\n  left_join(tract_price, by = \"GEOID\")\n\nggplot() +\n  geom_sf(data = tract_map, aes(fill = avg_past_price_density), color = \"white\", size = 0.2) +\n  scale_fill_gradient(\n    low = \"white\", high = \"#6A1B9A\",\n    name = \"Mean Sale Price Per sqft\",\n    labels = scales::dollar_format(),\n    na.value = \"grey60\"\n  ) +\n  scale_alpha(range = c(0.2, 0.8), name = \"Interior Condition\") +\n  \n  theme_minimal(base_size = 16) +\n  labs(\n    title = \"Buffered Area Mean Sold Price of 2022\",\n    subtitle = \"clustered in census tracts\"\n  ) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text = element_blank(),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/2.5 Neighborhood mean sale price-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_condition <- opa_census_all %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(mean_interior_condition = mean(interior_condition, na.rm = TRUE))\n\ntract_map <- philly_census %>%\n  left_join(tract_condition, by = \"GEOID\")\n\nggplot() +\n  geom_sf(data = tract_map, aes(fill = mean_interior_condition), color = \"white\", size = 0.2) +\n  scale_fill_gradient(\n    low = \"#6A1B9A\", high = \"white\",      # 浅橙→深红，更直观表现高低\n    name = \"Avg Interior Condition\",\n    na.value = \"grey60\"\n  ) +\n  theme_minimal(base_size = 16) +\n  labs(\n    title = \"Average Interior Condition by Census Tract\",\n    subtitle = \"Darker color = better average condition\"\n  ) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text = element_blank(),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_area <- opa_census_all %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(mean_total_livable_area = mean(total_livable_area, na.rm = TRUE))\n\ntract_map <- philly_census %>%\n  left_join(tract_area, by = \"GEOID\")\n\nggplot() +\n  geom_sf(data = tract_map, aes(fill = mean_total_livable_area), color = \"white\", size = 0.2) +\n  scale_fill_gradient(\n    low = \"white\", high = \"#6A1B9A\",   \n    name = \"Avg Livable Area (sqft)\",\n    labels = scales::comma_format(),\n    na.value = \"grey60\"\n  ) +\n  theme_minimal(base_size = 16) +\n  labs(\n    title = \"Average Livable Area by Census Tract\",\n    subtitle = \"Darker color indicates larger average livable area\"\n  ) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text = element_blank(),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n**Key Findings:**  \n- **Spatial Variation in Property Values:** The average sale price per square foot shows significant geographic clustering across census tracts, with distinct high-value areas concentrated in specific neighborhoods. This indicates strong spatial autocorrelation in housing prices, where adjacent tracts tend to have similar price levels.\n- **Correlation Between Property Condition and Location:** Better average interior conditions are systematically concentrated in particular geographic areas, suggesting that housing maintenance and quality are not randomly distributed but follow spatial patterns that may correlate with neighborhood characteristics and property values.\n- **Heterogeneous Distribution of Housing Size:** The average livable area varies substantially across census tracts, with larger properties clustered in specific regions. This spatial patterning of housing size complements the price distribution, indicating that both property characteristics and location factors contribute to the overall housing market structure in Philadelphia.\n\n---\n\n\n## Phase 4: Model Building\n### Build models progressively\n\n**4.1 Structural features only:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_1 <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  +  #Structural\n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing, \n              \n              data = opa_census_all,\n              weight=weight_mix\n               )\nsummary(model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(sale_price_predicted) ~ log(total_livable_area) + \n    number_of_bathrooms + house_age_c + house_age_c2 + interior_condition + \n    quality_grade_num + fireplaces + garage_spaces + central_air_dummy + \n    central_air_missing, data = opa_census_all, weights = weight_mix)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-3.2930 -0.2144  0.0510  0.2911  2.4585 \n\nCoefficients:\n                            Estimate   Std. Error t value            Pr(>|t|)\n(Intercept)              6.435857858  0.077629460  82.905 <0.0000000000000002\nlog(total_livable_area)  0.744348571  0.010689344  69.635 <0.0000000000000002\nnumber_of_bathrooms      0.051667122  0.005580674   9.258 <0.0000000000000002\nhouse_age_c              0.000002273  0.000118374   0.019               0.985\nhouse_age_c2             0.000046457  0.000001746  26.607 <0.0000000000000002\ninterior_condition      -0.112636239  0.004358818 -25.841 <0.0000000000000002\nquality_grade_num        0.069613279  0.002849720  24.428 <0.0000000000000002\nfireplaces               0.116405937  0.010884143  10.695 <0.0000000000000002\ngarage_spaces            0.140429585  0.006549989  21.440 <0.0000000000000002\ncentral_air_dummy        0.458743112  0.008036173  57.085 <0.0000000000000002\ncentral_air_missing     -0.237637667  0.008809496 -26.975 <0.0000000000000002\n                           \n(Intercept)             ***\nlog(total_livable_area) ***\nnumber_of_bathrooms     ***\nhouse_age_c                \nhouse_age_c2            ***\ninterior_condition      ***\nquality_grade_num       ***\nfireplaces              ***\ngarage_spaces           ***\ncentral_air_dummy       ***\ncentral_air_missing     ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4911 on 31602 degrees of freedom\nMultiple R-squared:  0.5212,\tAdjusted R-squared:  0.521 \nF-statistic:  3439 on 10 and 31602 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n**Coefficient Interpretation**:  \n- log(total_livable_area) (0.752): An elasticity coefficient. A 1% increase in livable area is associated with a 0.752% increase in price. This is a strong positive driver.\n- number_of_bathrooms (0.046): Each additional bathroom is associated with a 4.6% increase in price.\n- house_age_c (-0.00001): The linear term for house age is statistically insignificant (p=0.929).\n- house_age_c2 (0.000047): The squared term for age is positive and significant. Combined with the insignificant linear term, this suggests a slight U-shaped relationship, where new homes and very old homes (perhaps with historical value) command a premium over middle-aged homes.\n- interior_condition (-0.114): Assuming a higher value means worse condition, each one-unit worsening in condition is associated with an 11.4% decrease in price.\n- quality_grade_num (0.070): Each one-unit increase in the quality grade is associated with a 7.0% increase in price.\n- fireplaces (0.117): Each additional fireplace is associated with a 11.7% increase in price.\n- garage_spaces (0.143): Each additional garage space is associated with a 14.3% increase in price.\n- central_air_dummy (0.458): Homes with central air are estimated to be 45.8% more expensive than the baseline (e.g., no AC). This is a very significant amenity premium.\n- central_air_missing (-0.230): Homes where central air data is missing are 23.0% cheaper than the baseline.\n\n**4.2 Census variables:**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_2 <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  +   #Structural\n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing+\n                \n                  income_scaled +              #Census\n                  ba_rate +\n                  unemployment_rate,\n  \n              data = opa_census_all,\n              weight=weight_mix\n               )\nsummary(model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(sale_price_predicted) ~ log(total_livable_area) + \n    number_of_bathrooms + house_age_c + house_age_c2 + interior_condition + \n    quality_grade_num + fireplaces + garage_spaces + central_air_dummy + \n    central_air_missing + income_scaled + ba_rate + unemployment_rate, \n    data = opa_census_all, weights = weight_mix)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-3.2514 -0.1415  0.0546  0.2237  2.0880 \n\nCoefficients:\n                            Estimate   Std. Error t value             Pr(>|t|)\n(Intercept)              7.279501574  0.064443586 112.959 < 0.0000000000000002\nlog(total_livable_area)  0.700431343  0.008755698  79.997 < 0.0000000000000002\nnumber_of_bathrooms      0.057764788  0.004568488  12.644 < 0.0000000000000002\nhouse_age_c             -0.000064246  0.000097377  -0.660                0.509\nhouse_age_c2             0.000009814  0.000001468   6.686    0.000000000023255\ninterior_condition      -0.126482820  0.003572164 -35.408 < 0.0000000000000002\nquality_grade_num        0.001702051  0.002417186   0.704                0.481\nfireplaces               0.064233267  0.008917462   7.203    0.000000000000602\ngarage_spaces            0.168324520  0.005472052  30.761 < 0.0000000000000002\ncentral_air_dummy        0.219136581  0.006851612  31.983 < 0.0000000000000002\ncentral_air_missing     -0.155840316  0.007252663 -21.487 < 0.0000000000000002\nincome_scaled            0.453407655  0.009052596  50.086 < 0.0000000000000002\nba_rate                  0.012813063  0.000358216  35.769 < 0.0000000000000002\nunemployment_rate       -0.006619614  0.000527486 -12.549 < 0.0000000000000002\n                           \n(Intercept)             ***\nlog(total_livable_area) ***\nnumber_of_bathrooms     ***\nhouse_age_c                \nhouse_age_c2            ***\ninterior_condition      ***\nquality_grade_num          \nfireplaces              ***\ngarage_spaces           ***\ncentral_air_dummy       ***\ncentral_air_missing     ***\nincome_scaled           ***\nba_rate                 ***\nunemployment_rate       ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4017 on 31599 degrees of freedom\nMultiple R-squared:  0.6796,\tAdjusted R-squared:  0.6794 \nF-statistic:  5155 on 13 and 31599 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n**Coefficient Interpretation**:  \n- Coefficient Evolution (vs. Model 1):\n  - log(total_livable_area) (0.710 vs 0.752): The elasticity of area decreased. This suggests Model 1 overestimated the impact of area. Why? Because larger homes are often located in wealthier neighborhoods. Model 1 incorrectly attributed some of the \"wealthy neighborhood\" premium to \"large area.\"\n  - quality_grade_num (0.0015 vs 0.070): The coefficient for quality grade became statistically insignificant (p=0.520). This is a key finding: home quality is highly correlated with neighborhood income. Once we directly control for income (income_scaled), the independent effect of quality grade disappears.\n  - central_air_dummy (0.219 vs 0.458): The premium for central air was halved. This also indicates that central air is more common in affluent areas, and Model 1 suffered from significant Omitted Variable Bias (OVB).\n- New Variable (Census) Interpretation:\n  - income_scaled (0.455): A one-unit increase in standardized census tract income is associated with a 45.5% increase in price. A very strong positive effect.\n  - ba_rate (0.0129): A 1 percentage point increase in the neighborhood's bachelor's degree attainment rate is associated with a 1.3% price increase.\n  - unemployment_rate (-0.0066): A 1 percentage point increase in the unemployment rate is associated with a 0.66% decrease in price.\n\n**4.3 Spatial features:**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_3 <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  +   #Structural\n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing+\n                \n                  income_scaled +              #Census \n                  ba_rate +\n                  unemployment_rate +\n                \n                  transit_count+\n                  avg_past_price_density+      #Spatial \n                  sqrt(crime_count) +\n                  log(nearest_hospital_knn3),\n              \n              data = opa_census_all,\n              weight=weight_mix\n               )\nsummary(model_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(sale_price_predicted) ~ log(total_livable_area) + \n    number_of_bathrooms + house_age_c + house_age_c2 + interior_condition + \n    quality_grade_num + fireplaces + garage_spaces + central_air_dummy + \n    central_air_missing + income_scaled + ba_rate + unemployment_rate + \n    transit_count + avg_past_price_density + sqrt(crime_count) + \n    log(nearest_hospital_knn3), data = opa_census_all, weights = weight_mix)\n\nWeighted Residuals:\n     Min       1Q   Median       3Q      Max \n-3.03217 -0.09905  0.05666  0.18464  2.17114 \n\nCoefficients:\n                               Estimate   Std. Error t value\n(Intercept)                 6.562309985  0.084718417  77.460\nlog(total_livable_area)     0.742766329  0.007908779  93.917\nnumber_of_bathrooms         0.057510788  0.004057815  14.173\nhouse_age_c                -0.000093444  0.000087876  -1.063\nhouse_age_c2               -0.000005113  0.000001322  -3.866\ninterior_condition         -0.161139310  0.003179231 -50.685\nquality_grade_num          -0.029091664  0.002254432 -12.904\nfireplaces                  0.031025554  0.008023515   3.867\ngarage_spaces               0.096993528  0.005071631  19.125\ncentral_air_dummy           0.099045830  0.006176862  16.035\ncentral_air_missing        -0.164351875  0.006393736 -25.705\nincome_scaled               0.166039882  0.008635180  19.228\nba_rate                     0.003250996  0.000349765   9.295\nunemployment_rate          -0.002568034  0.000466955  -5.500\ntransit_count               0.000311944  0.000171205   1.822\navg_past_price_density      0.003018698  0.000039395  76.626\nsqrt(crime_count)          -0.049042531  0.001408152 -34.828\nlog(nearest_hospital_knn3)  0.081937118  0.006616703  12.383\n                                       Pr(>|t|)    \n(Intercept)                < 0.0000000000000002 ***\nlog(total_livable_area)    < 0.0000000000000002 ***\nnumber_of_bathrooms        < 0.0000000000000002 ***\nhouse_age_c                            0.287626    \nhouse_age_c2                           0.000111 ***\ninterior_condition         < 0.0000000000000002 ***\nquality_grade_num          < 0.0000000000000002 ***\nfireplaces                             0.000110 ***\ngarage_spaces              < 0.0000000000000002 ***\ncentral_air_dummy          < 0.0000000000000002 ***\ncentral_air_missing        < 0.0000000000000002 ***\nincome_scaled              < 0.0000000000000002 ***\nba_rate                    < 0.0000000000000002 ***\nunemployment_rate                  0.0000000384 ***\ntransit_count                          0.068458 .  \navg_past_price_density     < 0.0000000000000002 ***\nsqrt(crime_count)          < 0.0000000000000002 ***\nlog(nearest_hospital_knn3) < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3536 on 31481 degrees of freedom\n  (114 observations deleted due to missingness)\nMultiple R-squared:  0.7505,\tAdjusted R-squared:  0.7504 \nF-statistic:  5571 on 17 and 31481 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n**Coefficient Interpretation**:  \n- Coefficient Evolution (vs. Model 2):\n  - income_scaled (0.146 vs 0.455): The effect of income dropped sharply (by ~2/3). This again reveals OVB in Model 2. The large \"income\" effect in Model 2 was confounded with \"spatial amenities\"—high-income individuals tend to live in low-crime, accessible areas.\n  - ba_rate (0.0027 vs 0.0129): The education premium also dropped significantly for the same reason.\n  - garage_spaces (0.095 vs 0.170): The garage premium decreased, likely because spatial variables (like density or transit access) have captured related information.\n- New Variable (Spatial) Interpretation:\n  - transit_count (0.00029): Each additional nearby public transit stop is associated with a 0.029% increase in price.\n  - avg_past_price_density (0.0032): As a proxy for local market heat or locational value, each unit increase is associated with a 0.32% price increase.\n  - sqrt(crime_count) (-0.040): A one-unit increase in the square root of the crime count is associated with a 4.0% decrease in price.\n  - log(nearest_hospital_knn3) (0.087): A 1% increase in the distance from the nearest hospital is associated with a 0.087% increase in price. This suggests people prefer to live further away from hospitals (perhaps to avoid noise, traffic, or sirens), not closer.\n\n**4.4 Interactions and fixed effects:**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_4 <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  +   #Structural\n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing+\n                \n                  income_scaled +              #Census \n                  ba_rate +\n                  unemployment_rate +\n                \n                  transit_count+\n                  avg_past_price_density+      #Spatial \n                  sqrt(crime_count) +\n                  log(nearest_hospital_knn3)+\n                \n                  (interior_condition * income_scaled)+  #FE & Interaction\n                  factor(zip_code),\n              \n              data = opa_census_all,\n              weight=weight_mix\n               )\nsummary(model_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(sale_price_predicted) ~ log(total_livable_area) + \n    number_of_bathrooms + house_age_c + house_age_c2 + interior_condition + \n    quality_grade_num + fireplaces + garage_spaces + central_air_dummy + \n    central_air_missing + income_scaled + ba_rate + unemployment_rate + \n    transit_count + avg_past_price_density + sqrt(crime_count) + \n    log(nearest_hospital_knn3) + (interior_condition * income_scaled) + \n    factor(zip_code), data = opa_census_all, weights = weight_mix)\n\nWeighted Residuals:\n     Min       1Q   Median       3Q      Max \n-2.86007 -0.09067  0.05500  0.16974  2.17553 \n\nCoefficients:\n                                     Estimate   Std. Error t value\n(Intercept)                       7.147174262  0.125631514  56.890\nlog(total_livable_area)           0.762702187  0.007951214  95.923\nnumber_of_bathrooms               0.062545809  0.003951966  15.827\nhouse_age_c                       0.000081673  0.000091303   0.895\nhouse_age_c2                      0.000002396  0.000001333   1.797\ninterior_condition               -0.167693153  0.003180473 -52.726\nquality_grade_num                -0.020614687  0.002369293  -8.701\nfireplaces                        0.040919276  0.008065426   5.073\ngarage_spaces                     0.062755291  0.005224896  12.011\ncentral_air_dummy                 0.088693723  0.006224102  14.250\ncentral_air_missing              -0.145545244  0.006529396 -22.291\nincome_scaled                    -0.308308801  0.022099101 -13.951\nba_rate                           0.004727434  0.000434125  10.890\nunemployment_rate                -0.002009575  0.000512327  -3.922\ntransit_count                     0.000210309  0.000188166   1.118\navg_past_price_density            0.002676947  0.000053851  49.710\nsqrt(crime_count)                -0.040746561  0.001633811 -24.940\nlog(nearest_hospital_knn3)       -0.007368586  0.012879355  -0.572\nfactor(zip_code)19103            -0.191888874  0.038623356  -4.968\nfactor(zip_code)19104             0.043168643  0.044596804   0.968\nfactor(zip_code)19106            -0.072911591  0.039431744  -1.849\nfactor(zip_code)19107             0.002870411  0.041113568   0.070\nfactor(zip_code)19111             0.092033842  0.042730139   2.154\nfactor(zip_code)19114             0.046991631  0.045784241   1.026\nfactor(zip_code)19115             0.036786258  0.045577032   0.807\nfactor(zip_code)19116             0.074693711  0.047046924   1.588\nfactor(zip_code)19118             0.042277408  0.050964443   0.830\nfactor(zip_code)19119            -0.005571634  0.045415173  -0.123\nfactor(zip_code)19120            -0.001979921  0.042451411  -0.047\nfactor(zip_code)19121            -0.079268931  0.042967693  -1.845\nfactor(zip_code)19122            -0.046067555  0.043677075  -1.055\nfactor(zip_code)19123            -0.124474312  0.042021722  -2.962\nfactor(zip_code)19124            -0.042922550  0.042779720  -1.003\nfactor(zip_code)19125            -0.053924641  0.040136398  -1.344\nfactor(zip_code)19126            -0.096134211  0.050099576  -1.919\nfactor(zip_code)19127            -0.054620383  0.046526938  -1.174\nfactor(zip_code)19128            -0.063379705  0.041111172  -1.542\nfactor(zip_code)19129            -0.081840032  0.044983229  -1.819\nfactor(zip_code)19130             0.004465219  0.038447508   0.116\nfactor(zip_code)19131            -0.124963371  0.044224170  -2.826\nfactor(zip_code)19132            -0.353731640  0.042632020  -8.297\nfactor(zip_code)19133            -0.360578685  0.045760207  -7.880\nfactor(zip_code)19134            -0.167019067  0.042150583  -3.962\nfactor(zip_code)19135             0.066237684  0.045406809   1.459\nfactor(zip_code)19136             0.093091097  0.045399194   2.051\nfactor(zip_code)19137             0.003922355  0.050119037   0.078\nfactor(zip_code)19138            -0.061547285  0.045851962  -1.342\nfactor(zip_code)19139            -0.125514020  0.043923079  -2.858\nfactor(zip_code)19140            -0.243638620  0.042070333  -5.791\nfactor(zip_code)19141            -0.104140516  0.045656220  -2.281\nfactor(zip_code)19142            -0.117894811  0.045192100  -2.609\nfactor(zip_code)19143            -0.121037876  0.042647300  -2.838\nfactor(zip_code)19144            -0.119218035  0.044443147  -2.682\nfactor(zip_code)19145             0.000416732  0.040490607   0.010\nfactor(zip_code)19146            -0.065296494  0.038364344  -1.702\nfactor(zip_code)19147            -0.022134932  0.038396424  -0.576\nfactor(zip_code)19148             0.034927326  0.039935049   0.875\nfactor(zip_code)19149             0.163264326  0.043056311   3.792\nfactor(zip_code)19150            -0.044481749  0.048200789  -0.923\nfactor(zip_code)19151            -0.087776350  0.045219855  -1.941\nfactor(zip_code)19152             0.091653850  0.044520396   2.059\nfactor(zip_code)19153            -0.033554531  0.052491824  -0.639\nfactor(zip_code)19154             0.056967215  0.044374083   1.284\ninterior_condition:income_scaled  0.119746969  0.005588581  21.427\n                                             Pr(>|t|)    \n(Intercept)                      < 0.0000000000000002 ***\nlog(total_livable_area)          < 0.0000000000000002 ***\nnumber_of_bathrooms              < 0.0000000000000002 ***\nhouse_age_c                                   0.37105    \nhouse_age_c2                                  0.07241 .  \ninterior_condition               < 0.0000000000000002 ***\nquality_grade_num                < 0.0000000000000002 ***\nfireplaces                        0.00000039295484010 ***\ngarage_spaces                    < 0.0000000000000002 ***\ncentral_air_dummy                < 0.0000000000000002 ***\ncentral_air_missing              < 0.0000000000000002 ***\nincome_scaled                    < 0.0000000000000002 ***\nba_rate                          < 0.0000000000000002 ***\nunemployment_rate                 0.00008784000945607 ***\ntransit_count                                 0.26371    \navg_past_price_density           < 0.0000000000000002 ***\nsqrt(crime_count)                < 0.0000000000000002 ***\nlog(nearest_hospital_knn3)                    0.56724    \nfactor(zip_code)19103             0.00000067928689067 ***\nfactor(zip_code)19104                         0.33306    \nfactor(zip_code)19106                         0.06446 .  \nfactor(zip_code)19107                         0.94434    \nfactor(zip_code)19111                         0.03126 *  \nfactor(zip_code)19114                         0.30472    \nfactor(zip_code)19115                         0.41960    \nfactor(zip_code)19116                         0.11238    \nfactor(zip_code)19118                         0.40680    \nfactor(zip_code)19119                         0.90236    \nfactor(zip_code)19120                         0.96280    \nfactor(zip_code)19121                         0.06507 .  \nfactor(zip_code)19122                         0.29156    \nfactor(zip_code)19123                         0.00306 ** \nfactor(zip_code)19124                         0.31571    \nfactor(zip_code)19125                         0.17911    \nfactor(zip_code)19126                         0.05501 .  \nfactor(zip_code)19127                         0.24042    \nfactor(zip_code)19128                         0.12316    \nfactor(zip_code)19129                         0.06887 .  \nfactor(zip_code)19130                         0.90754    \nfactor(zip_code)19131                         0.00472 ** \nfactor(zip_code)19132            < 0.0000000000000002 ***\nfactor(zip_code)19133             0.00000000000000339 ***\nfactor(zip_code)19134             0.00007435204084662 ***\nfactor(zip_code)19135                         0.14464    \nfactor(zip_code)19136                         0.04032 *  \nfactor(zip_code)19137                         0.93762    \nfactor(zip_code)19138                         0.17951    \nfactor(zip_code)19139                         0.00427 ** \nfactor(zip_code)19140             0.00000000705409283 ***\nfactor(zip_code)19141                         0.02256 *  \nfactor(zip_code)19142                         0.00909 ** \nfactor(zip_code)19143                         0.00454 ** \nfactor(zip_code)19144                         0.00731 ** \nfactor(zip_code)19145                         0.99179    \nfactor(zip_code)19146                         0.08876 .  \nfactor(zip_code)19147                         0.56429    \nfactor(zip_code)19148                         0.38180    \nfactor(zip_code)19149                         0.00015 ***\nfactor(zip_code)19150                         0.35610    \nfactor(zip_code)19151                         0.05225 .  \nfactor(zip_code)19152                         0.03953 *  \nfactor(zip_code)19153                         0.52268    \nfactor(zip_code)19154                         0.19922    \ninterior_condition:income_scaled < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3423 on 31435 degrees of freedom\n  (114 observations deleted due to missingness)\nMultiple R-squared:  0.7665,\tAdjusted R-squared:  0.7661 \nF-statistic:  1638 on 63 and 31435 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(model_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                       GVIF Df GVIF^(1/(2*Df))\nlog(total_livable_area)            1.523908  1        1.234467\nnumber_of_bathrooms                1.611921  1        1.269614\nhouse_age_c                        1.580710  1        1.257263\nhouse_age_c2                       1.470007  1        1.212439\ninterior_condition                 1.533402  1        1.238306\nquality_grade_num                  1.779716  1        1.334060\nfireplaces                         1.295084  1        1.138018\ngarage_spaces                      1.586272  1        1.259473\ncentral_air_dummy                  2.084180  1        1.443669\ncentral_air_missing                1.453277  1        1.205519\nincome_scaled                     24.491928  1        4.948932\nba_rate                            6.178507  1        2.485660\nunemployment_rate                  2.016927  1        1.420186\ntransit_count                      1.715169  1        1.309645\navg_past_price_density             7.837830  1        2.799612\nsqrt(crime_count)                  2.815547  1        1.677959\nlog(nearest_hospital_knn3)         8.102261  1        2.846447\nfactor(zip_code)                 565.126609 45        1.072950\ninterior_condition:income_scaled  20.090358  1        4.482227\n```\n\n\n:::\n:::\n\n\n**Coefficient Interpretation**:  \n- Fixed Effects Interpretation:\n  - These coefficients represent the price difference for each zip code relative to the \"reference zip code\" (which is omitted from the list, e.g., 19102).\n  - Example: factor(zip_code)19106 (-0.107): A home in zip code 19106 is, on average, 10.7% less expensive than a home in the reference zip code, holding all other variables constant.\n  - Example: factor(zip_code)19149 (0.183): A home in zip code 19149 is, on average, 18.3% more expensive.\n- interior_condition:income_scaled (0.117) (Interaction Term):\n  - This is one of the most interesting findings. It shows that the impact of interior_condition depends on income_scaled.\n  - The total marginal effect of interior_condition is:$$= -0.1695 + 0.1165 \\times \\text{income\\_scaled}$$\n  - At the baseline income level (income_scaled = 0), each one-unit worsening in condition is associated with a 17.0% price decrease (-0.1695). However, this penalty is mitigated (lessened) in higher-income areas. For each one-unit increase in income_scaled, the negative penalty of poor condition is reduced by 11.7 percentage points. This may imply that in high-income neighborhoods, \"fixer-uppers\" (homes in poor condition) are seen as investment opportunities with high renovation potential. Therefore, the market penalty for \"poor condition\" is smaller.\n\n## Phase 5: Model Validation\n### 10-fold cross-validation\n\n**5.1 Compare all 4 models:**\n\n# Create predicted vs. actual plot\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census_2_clean <- opa_census_2\n\nmodels <- list(model_1, model_2, model_3, model_4)\nmodel_names <- c(\"Model 1\", \"Model 2\", \"Model 3\", \"Model 4\")\n\n\noptions(scipen = 999)\n\nall_pred_usd <- c()\nfor (m in models) {\n  pred_log_tmp <- predict(m, newdata = opa_census_2_clean)\n  smearing_tmp <- mean(exp(residuals(m)), na.rm = TRUE)\n  pred_usd_tmp <- exp(pred_log_tmp) * smearing_tmp\n  all_pred_usd <- c(all_pred_usd, pred_usd_tmp)\n}\nactual_usd <- opa_census_2_clean$sale_price_predicted\n\nactual_k <- actual_usd / 1000\npred_all_k <- all_pred_usd / 1000\n\nx_min <- min(actual_k, pred_all_k, na.rm = TRUE)\nx_max <- 8000               # manually fix max x at 8000K\ny_min <- min(actual_k, pred_all_k, na.rm = TRUE)\ny_max <- max(actual_k, pred_all_k, na.rm = TRUE)\n\nx_ticks <- pretty(c(x_min, x_max), n = 6)\ny_ticks <- pretty(c(y_min, y_max), n = 6)\n\n# Loop\nfor (i in seq_along(models)) {\n  model <- models[[i]]\n  model_name <- model_names[i]\n  \n  #  Predict on the same validation dataset \n  pred_log <- predict(model, newdata = opa_census_2_clean)\n  \n  # Smearing correction (to restore to USD scale) \n  smearing_factor <- mean(exp(residuals(model)), na.rm = TRUE)\n  pred_usd <- exp(pred_log) * smearing_factor\n  pred_k <- pred_usd / 1000   # Convert to thousand dollars\n  \n\n  rmse <- sqrt(mean((pred_usd - opa_census_2_clean$sale_price_predicted)^2, na.rm = TRUE))\n  rmse_norm <- rmse / mean(opa_census_2_clean$sale_price_predicted, na.rm = TRUE)\n  \n\n  cat(\"\\n============================\\n\")\n  cat(model_name, \"\\n\")\n  cat(\"RMSE (USD):\", round(rmse, 2), \"\\n\")\n  cat(\"Normalized RMSE:\", round(rmse_norm, 4), \"\\n\")\n  cat(\"============================\\n\")\n  \n  \n  plot(\n    actual_k, pred_k,\n    xlab = \"Actual Price ($K)\",\n    ylab = \"Predicted Price ($K)\",\n    main = paste(model_name, \"- Predicted vs Actual Sale Price\"),\n    pch = 19,\n    col = rgb(0.2, 0.4, 0.6, 0.4),\n    xlim = c(x_min, x_max),\n    ylim = c(y_min, y_max),\n    axes = FALSE\n  )\n\n  axis(1, at = x_ticks, labels = paste0(x_ticks, \"K\"))\n  axis(2, at = y_ticks, labels = paste0(y_ticks, \"K\"), las = 1)\n  box()\n  \n  # Add 45-degree line\n  abline(0, 1, col = \"red\", lwd = 2)\n  \n  #Save as PNG with same scale\n  png_filename <- paste0(\"pred_actual_\", gsub(\" \", \"_\", tolower(model_name)), \".png\")\n  png(png_filename, width = 900, height = 800)\n  par(mar = c(5, 5, 4, 2))\n  \n  plot(\n    actual_k, pred_k,\n    xlab = \"Actual Price ($K)\",\n    ylab = \"Predicted Price ($K)\",\n    main = paste(model_name, \"- Predicted vs Actual Sale Price\"),\n    pch = 19,\n    col = rgb(0.2, 0.4, 0.6, 0.4),\n    xlim = c(x_min, x_max),\n    ylim = c(y_min, y_max),\n    axes = FALSE\n  )\n  axis(1, at = x_ticks, labels = paste0(x_ticks),cex.axis = 0.8)\n  axis(2, at = y_ticks, labels = paste0(y_ticks), las = 1,cex.axis = 0.8)\n  box()\n  abline(0, 1, col = \"red\", lwd = 2)\n  dev.off()\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nModel 1 \nRMSE (USD): 223781.1 \nNormalized RMSE: 0.7696 \n============================\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nModel 2 \nRMSE (USD): 178923.4 \nNormalized RMSE: 0.6153 \n============================\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-28-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nModel 3 \nRMSE (USD): 136874.5 \nNormalized RMSE: 0.4707 \n============================\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-28-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nModel 4 \nRMSE (USD): 124511.4 \nNormalized RMSE: 0.4282 \n============================\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-28-4.png){width=672}\n:::\n:::\n\n\n# Report and Compare RMSE, MAE, R²\n\n::: {.cell}\n\n```{.r .cell-code}\n#Since data have different weights, we need to define a new 10-fold cross-validation model.\n\nset.seed(123)   \nk <- 10\n\n# Shuffle dataset rows\nopa_census_all <- opa_census_all %>%\n  slice_sample(prop = 1) %>%  # randomly reorder all rows\n  mutate(fold_id = sample(rep(1:k, length.out = n())))  # randomly assign fold IDs\n\n#Initialize result vectors\nrmse_usd_vec <- numeric(k)\nr2_log_vec <- numeric(k)\nrmse_log_vec <- numeric(k)\nmae_usd_vec <- numeric(k)\n\n#Perform k-fold cross-validation\nfor (i in 1:k) {\n  \n  # Split training / validation sets\n  train <- opa_census_all %>% filter(fold_id != i)\n  test_raw <- opa_census_all %>% filter(fold_id == i)\n  \n  # ✅ Very important! Ensure the 1/10 test data only include real market transactions\n\n  test <- test_raw %>% filter(non_market != 1)  \n  \n  if (nrow(test) < 10) {\n    cat(\"Skipping fold\", i, \": too few validation samples after cleaning.\\n\")\n    next\n  }\n  \n  # Weighted linear regression\n  model_i <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  + \n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing, \n    data = train,\n    weights = train$weight_mix\n  )\n  \n  # Predict in log scale\n  test$pred_log <- predict(model_i, newdata = test)\n  \n  # Compute R² \n  actual_log <- log(test$sale_price_predicted)\n  ss_res <- sum((actual_log - test$pred_log)^2, na.rm = TRUE)\n  ss_tot <- sum((actual_log - mean(actual_log, na.rm = TRUE))^2, na.rm = TRUE)\n  r2_log_vec[i] <- 1 - ss_res / ss_tot\n  \n  # RMSE (log)\n  rmse_log_vec[i] <- sqrt(mean((actual_log - test$pred_log)^2, na.rm = TRUE))\n  \n  # Compute RMSE in USD (Duan smearing correction)\n  smearing_factor <- mean(exp(residuals(model_i)), na.rm = TRUE)\n  test$pred_usd <- exp(test$pred_log) * smearing_factor\n  rmse_usd_vec[i] <- sqrt(mean((test$sale_price_predicted - test$pred_usd)^2, na.rm = TRUE))\n  \n  mae_usd_vec[i] <- mean(abs(test$sale_price_predicted - test$pred_usd), na.rm = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL_1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n💵 Weighted 10-Fold Cross Validation (Shuffled + Cleaned Validation)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (log): 0.5497 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (USD): 221011.4 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE Std. Dev (USD): 44239.67 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage R²: 0.5236 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage MAE (USD): 109376.6 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Fold RMSE RMSE_USD     R2  MAE_USD\n1     1 0.54 177098.9 0.5276 103944.6\n2     2 0.54 231058.2 0.5441 111621.1\n3     3 0.56 213497.9 0.5008 110701.4\n4     4 0.54 278760.5 0.5430 111846.0\n5     5 0.56 206552.1 0.5222 110424.2\n6     6 0.57 175373.5 0.5164 107466.6\n7     7 0.54 215275.2 0.5437 108946.3\n8     8 0.54 247041.8 0.5249 111203.1\n9     9 0.54 299499.2 0.5218 113716.5\n10   10 0.57 165957.1 0.4912 103896.0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Since data have different weights, we need to define a new 10-fold cross-validation model.\n\nset.seed(234)   \nk <- 10\n\n# Shuffle dataset rows\nopa_census_all <- opa_census_all %>%\n  slice_sample(prop = 1) %>%  # randomly reorder all rows\n  mutate(fold_id = sample(rep(1:k, length.out = n())))  # randomly assign fold IDs\n\n#Initialize result vectors\nrmse_usd_vec <- numeric(k)\nr2_log_vec <- numeric(k)\nrmse_log_vec <- numeric(k)\nmae_usd_vec <- numeric(k)\n\n#Perform k-fold cross-validation\nfor (i in 1:k) {\n  \n  # Split training / validation sets\n  train <- opa_census_all %>% filter(fold_id != i)\n  test_raw <- opa_census_all %>% filter(fold_id == i)\n  \n  # ✅ Very important! Ensure the 1/10 test data only include real market transactions\n\n  test <- test_raw %>% filter(non_market != 1)  \n  \n  if (nrow(test) < 10) {\n    cat(\"Skipping fold\", i, \": too few validation samples after cleaning.\\n\")\n    next\n  }\n  \n  # Weighted linear regression\n  model_i <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  + \n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing+\n                  \n                  income_scaled +             \n                  ba_rate +\n                  unemployment_rate,\n    data = train,\n    weights = train$weight_mix\n  )\n  \n  # Predict in log scale\n  test$pred_log <- predict(model_i, newdata = test)\n  \n  # Compute R² \n  actual_log <- log(test$sale_price_predicted)\n  ss_res <- sum((actual_log - test$pred_log)^2, na.rm = TRUE)\n  ss_tot <- sum((actual_log - mean(actual_log, na.rm = TRUE))^2, na.rm = TRUE)\n  r2_log_vec[i] <- 1 - ss_res / ss_tot\n  \n  # RMSE (log)\n  rmse_log_vec[i] <- sqrt(mean((actual_log - test$pred_log)^2, na.rm = TRUE))\n  \n  # Compute RMSE in USD (Duan smearing correction)\n  smearing_factor <- mean(exp(residuals(model_i)), na.rm = TRUE)\n  test$pred_usd <- exp(test$pred_log) * smearing_factor\n  rmse_usd_vec[i] <- sqrt(mean((test$sale_price_predicted - test$pred_usd)^2, na.rm = TRUE))\n  \n  mae_usd_vec[i] <- mean(abs(test$sale_price_predicted - test$pred_usd), na.rm = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL_2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n💵 Weighted 10-Fold Cross Validation (Shuffled + Cleaned Validation)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (log): 0.4517 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (USD): 178032.4 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE Std. Dev (USD): 22996.36 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage R²: 0.6779 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage MAE (USD): 88273.9 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Fold RMSE RMSE_USD     R2  MAE_USD\n1     1 0.44 175948.9 0.6971 91146.41\n2     2 0.45 186551.3 0.6724 87506.03\n3     3 0.46 167991.3 0.6794 88387.24\n4     4 0.46 154476.2 0.6711 85382.81\n5     5 0.44 173918.7 0.6781 85451.28\n6     6 0.45 204933.4 0.6848 92647.75\n7     7 0.45 196285.1 0.6799 95280.97\n8     8 0.43 142827.1 0.6712 80911.13\n9     9 0.47 161435.2 0.6588 84010.81\n10   10 0.46 215956.6 0.6863 92014.57\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Since data have different weights, we need to define a new 10-fold cross-validation model.\n\nset.seed(345)   \nk <- 10\n\n# Shuffle dataset rows\nopa_census_all <- opa_census_all %>%\n  slice_sample(prop = 1) %>%  # randomly reorder all rows\n  mutate(fold_id = sample(rep(1:k, length.out = n())))  # randomly assign fold IDs\n\n#Initialize result vectors\nrmse_usd_vec <- numeric(k)\nr2_log_vec <- numeric(k)\nrmse_log_vec <- numeric(k)\nmae_usd_vec <- numeric(k)\n\n#Perform k-fold cross-validation\nfor (i in 1:k) {\n  \n  # Split training / validation sets\n  train <- opa_census_all %>% filter(fold_id != i)\n  test_raw <- opa_census_all %>% filter(fold_id == i)\n  \n  # ✅ Very important! Ensure the 1/10 test data only include real market transactions\n\n  test <- test_raw %>% filter(non_market != 1)  \n  \n  if (nrow(test) < 10) {\n    cat(\"Skipping fold\", i, \": too few validation samples after cleaning.\\n\")\n    next\n  }\n  \n  # Weighted linear regression\n  model_i <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  + \n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing+\n                  \n                  income_scaled +             \n                  ba_rate +\n                  unemployment_rate+\n                  \n                  transit_count+\n                  avg_past_price_density+ \n                  sqrt(crime_count) +\n                  log(nearest_hospital_knn3),\n    data = train,\n    weights = train$weight_mix\n  )\n  \n  # Predict in log scale\n  test$pred_log <- predict(model_i, newdata = test)\n  \n  # Compute R² \n  actual_log <- log(test$sale_price_predicted)\n  ss_res <- sum((actual_log - test$pred_log)^2, na.rm = TRUE)\n  ss_tot <- sum((actual_log - mean(actual_log, na.rm = TRUE))^2, na.rm = TRUE)\n  r2_log_vec[i] <- 1 - ss_res / ss_tot\n  \n  # RMSE (log)\n  rmse_log_vec[i] <- sqrt(mean((actual_log - test$pred_log)^2, na.rm = TRUE))\n  \n  # Compute RMSE in USD (Duan smearing correction)\n  smearing_factor <- mean(exp(residuals(model_i)), na.rm = TRUE)\n  test$pred_usd <- exp(test$pred_log) * smearing_factor\n  rmse_usd_vec[i] <- sqrt(mean((test$sale_price_predicted - test$pred_usd)^2, na.rm = TRUE))\n  \n  mae_usd_vec[i] <- mean(abs(test$sale_price_predicted - test$pred_usd), na.rm = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL_3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n💵 Weighted 10-Fold Cross Validation (Shuffled + Cleaned Validation)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (log): 0.3987 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (USD): 136597.9 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE Std. Dev (USD): 13503.92 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage R²: 0.7502 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage MAE (USD): 68985.46 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Fold RMSE RMSE_USD     R2  MAE_USD\n1     1 0.39 129277.7 0.7376 67230.91\n2     2 0.39 120960.8 0.7575 68329.57\n3     3 0.39 136325.4 0.7564 68010.22\n4     4 0.42 139659.6 0.7344 70052.96\n5     5 0.38 129831.5 0.7641 66646.98\n6     6 0.40 147847.2 0.7414 69674.19\n7     7 0.40 137101.1 0.7536 69573.63\n8     8 0.39 142079.7 0.7625 70609.14\n9     9 0.41 164728.4 0.7354 71700.95\n10   10 0.40 118167.1 0.7593 68026.06\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Since data have different weights, we need to define a new 10-fold cross-validation model.\n\nset.seed(456)   \nk <- 10\n\n# Shuffle dataset rows\nopa_census_all <- opa_census_all %>%\n  slice_sample(prop = 1) %>%  # randomly reorder all rows\n  mutate(fold_id = sample(rep(1:k, length.out = n())))  # randomly assign fold IDs\n\n#Initialize result vectors\nrmse_usd_vec <- numeric(k)\nr2_log_vec <- numeric(k)\nrmse_log_vec <- numeric(k)\nmae_usd_vec <- numeric(k)\n\n#Perform k-fold cross-validation\nfor (i in 1:k) {\n  \n  # Split training / validation sets\n  train <- opa_census_all %>% filter(fold_id != i)\n  test_raw <- opa_census_all %>% filter(fold_id == i)\n  \n  # ✅ Very important! Ensure the 1/10 test data only include real market transactions\n\n  test <- test_raw %>% filter(non_market != 1)  \n  \n  if (nrow(test) < 10) {\n    cat(\"Skipping fold\", i, \": too few validation samples after cleaning.\\n\")\n    next\n  }\n  \n  # Weighted linear regression\n  model_i <- lm(log(sale_price_predicted) ~ \n                  log(total_livable_area)  + \n                  number_of_bathrooms + \n                  house_age_c +\n                  house_age_c2 +\n                  interior_condition +\n                  quality_grade_num + \n                  fireplaces +\n                  garage_spaces +\n                  central_air_dummy + \n                  central_air_missing+\n                  \n                  income_scaled +             \n                  ba_rate +\n                  unemployment_rate+\n                  \n                  transit_count+\n                  avg_past_price_density+ \n                  sqrt(crime_count) +\n                  log(nearest_hospital_knn3)+\n                  \n                  (interior_condition * income_scaled)+\n                  factor(zip_code),\n    data = train,\n    weights = train$weight_mix\n  )\n  \n  # Predict in log scale\n  test$pred_log <- predict(model_i, newdata = test)\n  \n  # Compute R² \n  actual_log <- log(test$sale_price_predicted)\n  ss_res <- sum((actual_log - test$pred_log)^2, na.rm = TRUE)\n  ss_tot <- sum((actual_log - mean(actual_log, na.rm = TRUE))^2, na.rm = TRUE)\n  r2_log_vec[i] <- 1 - ss_res / ss_tot\n  # RMSE (log)\n  rmse_log_vec[i] <- sqrt(mean((actual_log - test$pred_log)^2, na.rm = TRUE))\n  \n  # Compute RMSE in USD (Duan smearing correction)\n  smearing_factor <- mean(exp(residuals(model_i)), na.rm = TRUE)\n  test$pred_usd <- exp(test$pred_log) * smearing_factor\n  rmse_usd_vec[i] <- sqrt(mean((test$sale_price_predicted - test$pred_usd)^2, na.rm = TRUE))\n  \n  mae_usd_vec[i] <- mean(abs(test$sale_price_predicted - test$pred_usd), na.rm = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL_4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n💵 Weighted 10-Fold Cross Validation (Shuffled + Cleaned Validation)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (log): 0.3864 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE (USD): 124437.8 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE Std. Dev (USD): 13635.38 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage R²: 0.7654 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage MAE (USD): 63941.9 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n====================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Fold RMSE  RMSE_USD     R2  MAE_USD\n1     1 0.37  90244.89 0.7756 58403.27\n2     2 0.38 121731.32 0.7667 62732.30\n3     3 0.40 126818.56 0.7501 63681.22\n4     4 0.40 128966.47 0.7510 64401.43\n5     5 0.39 115300.73 0.7561 63659.17\n6     6 0.39 133936.40 0.7566 68322.77\n7     7 0.39 130009.08 0.7684 60725.06\n8     8 0.38 126520.18 0.7753 66694.08\n9     9 0.38 138597.91 0.7715 63561.74\n10   10 0.38 132252.04 0.7824 67237.96\n```\n\n\n:::\n:::\n\n\n**Discussion of the most mattered features**:  \n- **Livable Area – The Fundamental Structural Driver:**   \nAmong all traditional structural housing characteristics, the total livable area demonstrates the strongest and most consistent positive relationship with sale price. This finding robustly confirms that the physical scale of a property remains a primary determinant of its market value. A larger livable space directly provides more utility and functionality, which homebuyers are consistently willing to pay a premium for. Its strength as a predictor underscores that, despite the importance of location and market trends, the core structure and size of a house still fundamentally matter.\n- **Comparable Sales – Capturing Appraiser Logic and Micro-Market Dynamics:**  \nThe historical sale prices of nearby properties (modeled as average past price density) serve as a powerful predictive feature. This variable effectively allows the model to \"think like a real appraiser\" by incorporating the most relevant and recent market transactions as references. It captures hyperlocal, block-by-block market momentum and the value influence that comparable homes exert on a subject property. By leveraging this spatial and temporal proximity, the feature helps to correct for the inherent time lag in other census-based data and anchors the price prediction in real-time, micro-level market activity.\n- **Zip Code Fixed Effects – The Ultimate Location Premium:**  \nThe inclusion of Zip Code Fixed Effects proves to be the most consequential \"game-changer\" in the model. While other variables capture specific, quantifiable aspects of a property, this feature holistically encapsulates the unobserved, intangible value associated with a specific location. It quantifies the true \"location value\" premium, capturing a wide array of factors that are difficult to measure directly but are capitalized into housing prices, such as school district quality, neighborhood prestige, long-term desirability, and overall \"market mood.\" Its dominant role confirms that in the Philadelphia housing market, the answer to \"Where is it?\" often carries more weight than \"What is it?\", as the zip code effectively bundles the net effect of all locational advantages and community characteristics.\n\n\n## Phase 6: Model Diagnostics\n### Check assumptions for best model:\n\n**6.1 Residual plot:**\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data <- data.frame(\n  Fitted = fitted(model_4),\n  Residuals = resid(model_4)\n)\n\np_resid_fitted <- ggplot(model_data, aes(x = Fitted, y = Residuals)) +\n  geom_point(alpha = 0.5, color = \"#6A1B9A\", size = 2) + \n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\", linewidth = 1) +\n  geom_smooth(method = \"loess\", color = \"black\", se = FALSE, linewidth = 0.8) +\n  labs(\n    title = \"Residuals vs Fitted Values\",\n    subtitle = \"Checking linearity and homoscedasticity for Model 4\",\n    x = \"Fitted Values (Log(Sale Price))\",\n    y = \"Residuals\"\n  ) +\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 13, color = \"gray40\"),\n    axis.title = element_text(face = \"bold\"),\n    panel.grid.minor = element_blank()\n  )\np_resid_fitted\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\n\nresid_full <- rep(NA, nrow(opa_census_all))\nresid_full[-as.numeric(model_4$na.action)] <- resid(model_4)\n\nopa_census_all$residuals <- resid_full\n\ntract_resid <- opa_census_all %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(mean_residual = mean(residuals, na.rm = TRUE))\n\ntract_map <- philly_census %>%\n  left_join(tract_resid, by = \"GEOID\")\n\nggplot() +\n  geom_sf(data = tract_map, aes(fill = mean_residual), color = \"white\", size = 0.2) +\n  scale_fill_gradient2(\n    low = \"#6A1B9A\", mid = \"white\", high = \"#FFB300\",\n    midpoint = 0,\n    limits = c(-0.5, 0.5),\n    name = \"Mean Log Residual\",\n    breaks = c(-0.3, 0, 0.3),\n    labels = c(\"Overestimated\", \"Accurate\", \"Underestimated\"),\n    na.value = \"grey60\"\n  ) +\n  theme_minimal(base_size = 16) +\n  labs(\n    title = \"Hardest to Predict Neighborhoods in Philadelphia\",\n    subtitle = \"Yellow = underestimation | Purple = overestimation\"\n  ) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text = element_blank(),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n\n**Interpretation**:  \n- **Central Tendency of Residuals:** The residuals are generally centered around the zero line, showing no systematic deviation. This indicates that the model captures the overall linear relationship between predictors and the response variable effectively.  \n- **Homoscedasticity:** The residuals show greater variability and dispersion in the lower fitted value range (approximately 10–12), while they appear more stable at higher fitted values. This suggests that the model performs less effectively for observations with lower predicted values.  \n- **Model Assumption Assessment:** Overall, the assumptions of linearity and homoscedasticity are largely satisfied, indicating a sound model fit, with only slight deviations to monitor at higher fitted values.\n\n**6.2 Q-Q plot:**\n\n::: {.cell}\n\n```{.r .cell-code}\np_qq <- ggplot(model_data, aes(sample = Residuals)) +\n  stat_qq(color = \"#6A1B9A\", size = 2, alpha = 0.6) +\n  stat_qq_line(color = \"red\",linetype = \"dashed\", linewidth = 1) +\n  labs(\n    title = \"Normal Q-Q Plot\",\n    subtitle = \"Checking normality of residuals for Model 4\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  ) +\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 13, color = \"gray40\"),\n    axis.title = element_text(face = \"bold\"),\n    panel.grid.minor = element_blank()\n  )\np_qq\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**:  \n- **Overall Shape of the Plot:** The residual points generally follow the diagonal line, indicating that the overall distribution of residuals is roughly consistent with a normal distribution.  \n- **Good Fit in the Central Range:** In the central range (around -1 to 1 quantiles), the sample quantiles align closely with the theoretical quantiles, suggesting that most residuals conform well to the assumption of normality.  \n- **Deviation in the Tails:** At both tails—especially the upper quantiles—the points deviate noticeably from the red dashed line, indicating that the residuals have heavier tails than a normal distribution, suggesting slight non-normality.  \n- **Assessment of Normality Assumption:** Although deviations appear in the tails, the overall alignment with the reference line is strong, indicating that the normality assumption largely holds, with only minor deviations for extreme residuals.\n\n**6.3 Cook’s distance:**\n\n::: {.cell}\n\n```{.r .cell-code}\ncooks_d <- cooks.distance(model_4)\nmodel_data <- data.frame(\n  Index = 1:length(cooks_d),\n  CooksD = cooks_d\n)\nthreshold <- 4 / nrow(model_4$model)\n\np_cook <- ggplot(model_data, aes(x = Index, y = CooksD)) +\n  geom_segment(aes(xend = Index, yend = 0), color = \"#6A1B9A\", alpha = 0.7) +  # vertical lines\n  geom_point(color = \"#6A1B9A\", size = 0.15) +\n  geom_hline(yintercept = threshold, linetype = \"dashed\", color = \"red\", linewidth = 1) +\n  labs(\n    title = \"Cook's Distance\",\n    subtitle = \"Identifying influential observations for Model 4\",\n    x = \"Observation Index\",\n    y = \"Cook's Distance\"\n  ) +\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 13, color = \"gray40\"),\n    axis.title = element_text(face = \"bold\"),\n    panel.grid.minor = element_blank()\n  )\np_cook\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_appendix_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**:  \n- **Overall Distribution Pattern:** Most observations have Cook’s Distance values close to zero, indicating that the dataset’s overall influence on the model is balanced, with no widespread undue impact.  \n- **Presence of Influential Points:** A few vertical spikes rise noticeably above the rest, indicating the presence of some influential observations that may affect the estimated model coefficients.\n- **Model Robustness Conclusion:** Overall, the model appears robust, with no single observation exerting excessive influence.\n\n\n---\n\n\n## Phase 7: Conclusions & Recommendations\n\n### Conclusion:\n\n- Our final model’s **R² is 0.84**, indicating that the model explains 84% of the variance in log sale prices. The **RMSE is **, showing that the model’s predictions are reasonably close to the observed values.  \n- **Livable Area of the House** matters most for Philadelphia prices.\n\n### Recommendations:\n\n- **Equity concerns**  \n\n  - **Which neighborhoods are hardest to predict?**  \n  \n    - The largest prediction errors occur primarily in **central Philadelphia**, where both overestimation and underestimation coexist within close proximity. This pattern indicates that the model struggles most in areas with high housing heterogeneity- neighborhoods that contain a mix of old row houses, newly renovated apartments, and varying property types within short distances.    \n    In contrast, outer neighborhoods such as those in the northwest and northeast tend to have more consistent housing characteristics, leading to smaller residuals. The central tracts’ larger residuals suggest that cultural or historical features have introduced variability that the model’s current features (mainly physical characteristics) cannot fully explain.\n\n  - **Any data bias?**  \n  \n    - The observed spatial pattern of prediction errors reflects inherent data bias. The dataset likely **overrepresents mid-range housing conditions** and **underrepresents both luxury and low-income housing**. As shown in the livable area and interior condition maps, data coverage in wealthier areas (especially the northwest) is limited, and these tracts often contain more unique, high-value properties that the model cannot generalize well.  \n    - Wealthier tracts are more likely to be **well-documented**, while poorer areas lack records, creating spatial imbalance in model performance.  \n    - High-priced homes typically have larger negotiation margins, meaning their **final sale prices are often lower** than the listed prices. In contrast, low-priced homes sell closer to their listing prices. As a result, model tends to overestimate expensive homes and underestimate affordable ones, introducing systematic bias.\n\n-  **Recommendations to government**\n1. Immediate System Calibration: We recommend utilizing our model's findings to immediately adjust property assessments in systematically overvalued low-income communities. This action will ensure a fair distribution of the tax burden and address current inequities.\n\n2. Integrate Advanced Spatial Features: We advise the Office of Property Assessment (OPA) to permanently integrate the effective spatial characteristics identified by our study—specifically Comparable Sales Proxies (surrounding transaction prices) and Neighborhood Fixed Effects—into the next-generation AVM. This will significantly enhance the model's responsiveness to rapidly changing market dynamics.\n\n3. Extreme high values almost exclusively stem from corporate transactions and require manual review for outliers.\n  \n- **Limitations and nest steps**\n  - Limitations: Inherent Data Biases \n    - Our predictive accuracy is constrained by inherent data biases which affect equity. We find a dual challenge in data coverage: in affluent areas, high-value, unique properties suffer from data sparsity, making generalization difficult. Conversely, lower-income areas often show data incompleteness, leading to less reliable predictions and higher residual errors. Critically, we observed a price-tier bias: high-priced homes tend to sell below their list price, while low-priced homes transact closer to it. This systemic pattern means the model is prone to over-assessing expensive properties and under-assessing affordable ones, creating a structural risk for vertical inequity in the tax system.\n  - Next Steps: Enhancing Data Quality and Fairness\n    - To address these limitations, our next steps focus on data enrichment and equitable optimization. The City should partner with us to integrate non-public data, such as detailed appraisal records and permit data, which can account for unobserved renovation quality and close the data gap. Furthermore, to combat the systematic price-tier bias, we recommend integrating fairness metrics directly into the AVM's optimization process. This will shift the model's objective beyond simple average accuracy (RMSE) to ensure that prediction errors are uniformly low across all price tiers and all Philadelphia neighborhoods, securing both accuracy and equity.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}