{
  "hash": "0e5ec906e76db8f25dcf1181c676fd4f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Jinyang Xu\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n  cache: true\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(knitr)\nlibrary(tidycensus)\nlibrary(sf)\nlibrary(tigris)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\nlibrary(units)\n\n# Load spatial data\ncensus_api_key(\"fef2af5588030f3fd4b474bd111e0d63a7ec2837\")\n\npa_county <- st_read(\"data/Pennsylvania_County_Boundaries.shp\") \npa_hos <- st_read(\"data/hospitals.geojson\")\npa_tracts <- tracts(state = \"PA\", year = 2020, class = \"sf\")\n\n# Check that all data loaded correctly\n\nggplot(data = pa_county) +\n  geom_sf(fill = \"lightblue\", color = \"white\", size = 0.2) +\n  labs(title = \"Census Tracts in Philadelphia County, PA (2020)\",\n       caption = \"Source: US Census Bureau TIGER/Line\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = pa_tracts) +\n  geom_sf(fill = \"lightblue\", color = \"white\", size = 0.2) +\n  labs(title = \"Census Tracts in Philadelphia County, PA (2020)\",\n       caption = \"Source: US Census Bureau TIGER/Line\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\nst_crs(pa_hos)\nst_crs(pa_county)\nst_crs(pa_tracts)\n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n\n223 rows in the data.\n\n- How many census tracts?\n\n67 rows in the data.\n\n- What coordinate reference system is each dataset in?\n\nPA hospitals:EPSG 4326\nPA county boundaries:EPSG 3857\nPA census tracts:EPSG 4269\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_pop <- get_acs(\n  geography = \"tract\",\n  variables = \"B01003_001\",\n  state = \"PA\",\n  year = 2022,\n  geometry = FALSE\n)\n\npa_income <- get_acs(\n  geography = \"tract\",\n  variables = \"B19013_001\",\n  state = \"PA\",\n  year = 2022,\n  geometry = FALSE\n)\nage65_vars <- c(\n  \"B01001_020\", \"B01001_021\", \"B01001_022\", \"B01001_023\", \"B01001_024\", \"B01001_025\", # Male 65+\n  \"B01001_044\", \"B01001_045\", \"B01001_046\", \"B01001_047\", \"B01001_048\", \"B01001_049\"  # Female 65+\n)\n\npa_age65 <- get_acs(\n  geography = \"tract\",\n  variables = age65_vars,\n  state = \"PA\",\n  year = 2022,\n  geometry = FALSE\n) %>%\n  group_by(GEOID) %>%\n  summarize(age65_total = sum(estimate))\n\n\n\n# Join to tract boundaries\n\npa_demographics <- pa_tracts %>%\n  left_join(pa_pop %>% select(GEOID, total_pop = estimate), by = \"GEOID\") %>%\n  left_join(pa_income %>% select(GEOID, median_income = estimate), by = \"GEOID\") %>%\n  left_join(pa_age65, by = \"GEOID\") %>%\n  mutate(pct_65plus = 100 * age65_total / total_pop)\npa_demographics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3446 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -80.51985 ymin: 39.7198 xmax: -74.68956 ymax: 42.51607\nGeodetic CRS:  NAD83\nFirst 10 features:\n   STATEFP COUNTYFP TRACTCE       GEOID    NAME             NAMELSAD MTFCC\n1       42      095  017703 42095017703  177.03  Census Tract 177.03 G5020\n2       42      101  012204 42101012204  122.04  Census Tract 122.04 G5020\n3       42      129  804300 42129804300    8043    Census Tract 8043 G5020\n4       42      129  804801 42129804801 8048.01 Census Tract 8048.01 G5020\n5       42      129  805200 42129805200    8052    Census Tract 8052 G5020\n6       42      101  012203 42101012203  122.03  Census Tract 122.03 G5020\n7       42      101  013602 42101013602  136.02  Census Tract 136.02 G5020\n8       42      101  034502 42101034502  345.02  Census Tract 345.02 G5020\n9       42      101  000902 42101000902    9.02    Census Tract 9.02 G5020\n10      42      101  001201 42101001201   12.01   Census Tract 12.01 G5020\n   FUNCSTAT   ALAND AWATER    INTPTLAT     INTPTLON total_pop median_income\n1         S 3708021   9639 +40.6498956 -075.3948647      3197         87232\n2         S  879459  56473 +40.0009407 -075.2120769      3915         48000\n3         S 1014739      0 +40.2918690 -079.5478131      2012         54318\n4         S 6852606      0 +40.3011416 -079.6013733      2281         48412\n5         S 1873022      0 +40.1523157 -079.8745928      1865         44375\n6         S  227696      0 +40.0074872 -075.2093403      1074         63750\n7         S  246812      0 +39.9716057 -075.1800748      3975        116375\n8         S 1021734      0 +40.0814101 -075.0384569      5299         55439\n9         S  155167      0 +39.9471596 -075.1566389      2736         89063\n10        S  327555  30728 +39.9470373 -075.1799169      4323        116935\n   age65_total                       geometry pct_65plus\n1         1001 MULTIPOLYGON (((-75.4109 40...  31.310604\n2         1118 MULTIPOLYGON (((-75.22066 4...  28.556833\n3          491 MULTIPOLYGON (((-79.55534 4...  24.403579\n4          513 MULTIPOLYGON (((-79.62842 4...  22.490136\n5          347 MULTIPOLYGON (((-79.88358 4...  18.605898\n6           24 MULTIPOLYGON (((-75.21389 4...   2.234637\n7          393 MULTIPOLYGON (((-75.18637 3...   9.886792\n8          946 MULTIPOLYGON (((-75.04729 4...  17.852425\n9          702 MULTIPOLYGON (((-75.16017 3...  25.657895\n10         428 MULTIPOLYGON (((-75.18714 3...   9.900532\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(pa_demographics$median_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 63\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(pa_demographics$median_income, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70188\n```\n\n\n:::\n:::\n\n\npa_hos <- st_transform(pa_hos, st_crs(pa_county))\npa_tracts <- st_transform(pa_tracts, st_crs(pa_county))\n\n**Questions to answer:**\n- What year of ACS data are you using?\n\n2022\n\n- How many tracts have missing income data?\n\n63\n\n- What is the median income across all PA census tracts?\n\n$70188\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n\n# bottom 25%\nlow_income_threshold <- quantile(pa_demographics$median_income, 0.25, na.rm = TRUE)  \n# top 25%\nhigh_elderly_threshold <- quantile(pa_demographics$pct_65plus, 0.75, na.rm = TRUE)   \n\n\npa_vulnerable <- pa_demographics %>%\n  mutate(\n    vulnerable_income = median_income < low_income_threshold,\n    vulnerable_age = pct_65plus > high_elderly_threshold,\n    vulnerable = vulnerable_income & vulnerable_age\n  )\n\nvulnerable_count <- sum(pa_vulnerable$vulnerable, na.rm = TRUE)\ntotal_tracts <- nrow(pa_vulnerable)\nvulnerable_pct <- 100 * vulnerable_count / total_tracts\n\nvulnerable_count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 165\n```\n\n\n:::\n\n```{.r .cell-code}\nvulnerable_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.78816\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n\nI chose the bottom 25% of tracts based on median household income, which corresponds to tracts with income below approximately $54,000. This threshold identifies communities that are relatively low-income compared to the rest of Pennsylvania.\n\n- What elderly population threshold did you choose and why?\n\nElderly population threshold: I selected the top 25% of tracts by percentage of residents aged 65 and over, representing tracts where more than about 20.5% of residents are elderly. This captures areas with a significantly aging population that may face accessibility and healthcare challenges.\n\n- How many tracts meet your vulnerability criteria?\n\n165\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\n4.78816%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\npa_vul <- pa_vulnerable %>%\n  filter(vulnerable)\npa_vul_proj <- st_transform(pa_vul, 26917)\npa_hos_proj <- st_transform(pa_hos, 26917)\n\n# Calculate distance from each tract centroid to nearest hospital\n\nvul_center <- pa_vul_proj %>%\n  st_centroid()\n\nvul_center <- vul_center %>%\n  mutate(\n    nearest_idx = st_nearest_feature(., pa_hos_proj)  \n  ) %>%\n  mutate(\n    dist_mi = st_distance(., pa_hos_proj[nearest_idx, ], by_element = TRUE) %>%\n      set_units(\"mi\") %>%\n      drop_units() \n  )\n\nsummary_stats <- vul_center %>%\n  summarize(\n    avg_dist_mi = mean(dist_mi, na.rm = TRUE),\n    max_dist_mi = max(dist_mi, na.rm = TRUE),\n    over15_count = sum(dist_mi > 15, na.rm = TRUE),\n    total_vul = n()\n  ) %>%\n  mutate(\n    pct_over15 = 100 * over15_count / total_vul\n  )\n\nsummary_stats %>%\n  st_drop_geometry() %>%\n  kable(\n    caption = \"Table. Hospital Access Among Vulnerable Census Tracts in Pennsylvania\",\n    digits = 2,\n    align = \"lrrrr\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Table. Hospital Access Among Vulnerable Census Tracts in Pennsylvania\n\n|avg_dist_mi | max_dist_mi| over15_count| total_vul| pct_over15|\n|:-----------|-----------:|------------:|---------:|----------:|\n|4.75        |       19.18|            9|       165|       5.45|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n\n4.75miles\n\n- What is the maximum distance?\n\n19.16miles\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n\n9\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nvul_center <- vul_center %>%\n  mutate(\n    underserved= (as.numeric(dist_mi> 15))\n  )\n\nunder_count= sum(vul_center$underserved)  \nvul_pct= under_count/ nrow(vul_center)\nunder_count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code}\nvul_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05454545\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n\n9\n\n- What percentage of vulnerable tracts are underserved?\n\n5.45%\n\n- Does this surprise you? Why or why not?\n\nYes — I didn’t expect any tracts to be this far from a hospital. This suggests that while most of Pennsylvania’s vulnerable areas have reasonable healthcare access, a few rural or remote tracts still face significant geographic barriers to medical services.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_county <- st_transform(pa_county, crs=26917)\nvul_center<- st_transform(vul_center, crs=st_crs(pa_county))\n\nst_county <- st_join(\n  pa_county,\n  vul_center,\n  join  = st_contains,\n  left  = TRUE                # keep all counties\n)\n\n# Aggregate statistics by county\n\nagg_county <- st_county %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    vul_count= sum(vulnerable),\n    und_count= sum(underserved),\n    pct_vul_underserved = 100 * sum(vulnerable & underserved) / sum(vulnerable),\n    avg_dist_vulnerable = mean(dist_mi[vulnerable], na.rm = TRUE),\n    vul_pop = sum(total_pop[vulnerable]),\n    und_pop = sum(total_pop[underserved])\n  )\n\nagg_county <- agg_county %>%\n  mutate(across(where(is.numeric), ~replace(., is.na(.), 0)))\nagg_county\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 67 features and 7 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 539820.7 ymin: 4396937 xmax: 1034915 ymax: 4680425\nProjected CRS: NAD83 / UTM zone 17N\n# A tibble: 67 × 8\n   COUNTY_NAM vul_count und_count pct_vul_underserved avg_dist_vulnerable\n * <chr>          <dbl>     <dbl>               <dbl>               <dbl>\n 1 ADAMS              0         0                   0                0   \n 2 ALLEGHENY         22         0                   0                2.84\n 3 ARMSTRONG          1         0                   0               10.0 \n 4 BEAVER             5         0                   0                2.83\n 5 BEDFORD            2         0                   0                7.97\n 6 BERKS              0         0                   0                0   \n 7 BLAIR              3         0                   0                3.07\n 8 BRADFORD           1         1                 100               16.7 \n 9 BUCKS              0         0                   0                0   \n10 BUTLER             0         0                   0                0   \n# ℹ 57 more rows\n# ℹ 3 more variables: vul_pop <dbl>, und_pop <dbl>, geometry <MULTIPOLYGON [m]>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Step 6: Top 5 counties with highest % of underserved vulnerable tracts ---\ntop5_underserved <- agg_county %>%\n  st_drop_geometry() %>%\n  arrange(desc(pct_vul_underserved)) %>%\n  select(COUNTY_NAM, pct_vul_underserved, vul_count, und_count) %>%\n  head(5)\n\n# --- Step 7: Top 5 counties with largest vulnerable population far from hospitals ---\ntop5_vulpop_far <- agg_county %>%\n  st_drop_geometry() %>%\n  arrange(desc(und_pop)) %>%\n  select(COUNTY_NAM, und_pop, vul_pop, avg_dist_vulnerable) %>%\n  head(5)\n\n# --- Step 8: Display results ---\ntop5_underserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  COUNTY_NAM pct_vul_underserved vul_count und_count\n  <chr>                    <dbl>     <dbl>     <dbl>\n1 BRADFORD                   100         1         1\n2 FOREST                     100         1         1\n3 JUNIATA                    100         1         1\n4 MONROE                     100         1         1\n5 SULLIVAN                   100         1         1\n```\n\n\n:::\n\n```{.r .cell-code}\ntop5_vulpop_far\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  COUNTY_NAM und_pop vul_pop avg_dist_vulnerable\n  <chr>        <dbl>   <dbl>               <dbl>\n1 BRADFORD      5466    5466               16.7 \n2 CLEARFIELD    5285   13056               11.4 \n3 DAUPHIN       4392    8410                9.96\n4 POTTER        4257    9062                9.55\n5 CRAWFORD      2842    9072                8.35\n```\n\n\n:::\n:::\n\n+\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n\nBRADFORD\nFOREST\nJUNIATA\nMONROE\nSULLIVAN\n\n- Which counties have the most vulnerable people living far from hospitals?\n\nBRADFORD\nCLEARFIELD\nDAUPHIN\nPOTTER\nCRAWFORD\n\n- Are there any patterns in where underserved counties are located?\n\nThese are typically larger rural counties where population is dispersed and hospitals are sparse.\nUrban counties (like Philadelphia or Allegheny) rarely appear because of dense hospital networks.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nagg_county <- agg_county %>%\n  mutate(\n    z_vul_pop     = scales::rescale(vul_pop),       # vulnerability\n    z_underserved = scales::rescale(pct_vul_underserved), # service deficit\n    z_distance    = scales::rescale(avg_dist_vulnerable), # accessibility\n    priority_score = 0.25*z_vul_pop + 0.1*z_underserved + 0.65*z_distance\n  )\n\npriority_table <- agg_county %>%\n  arrange(desc(priority_score)) %>%\n  slice(1:10) %>%\n  transmute(\n    `County` = COUNTY_NAM,\n    `Priority Score` = round(priority_score*100, 2),\n    `Vulnerable Population` = comma(vul_pop),\n    `Avg. Dist. to Hospital (mi)` = round(avg_dist_vulnerable, 2),\n    `Underserved (%)` = percent(pct_vul_underserved / 100, accuracy = 0.01),\n    `Vulnerable Tracts` = vul_count,\n    `Underserved Tracts` = und_count,\n  )\n\npriority_table %>%\n  st_drop_geometry() %>%\n  kable(\n    caption = \"***Table 1. Top 10 Priority Counties for Healthcare Investment in Pennsylvania***\",\n    align = \"lrrrrrr\",\n    format = \"pipe\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: ***Table 1. Top 10 Priority Counties for Healthcare Investment in Pennsylvania***\n\n|County         | Priority Score| Vulnerable Population| Avg. Dist. to Hospital (mi)| Underserved (%)| Vulnerable Tracts| Underserved Tracts|\n|:--------------|--------------:|---------------------:|---------------------------:|---------------:|-----------------:|------------------:|\n|FOREST         |          76.09|                 2,701|                       18.12|         100.00%|                 1|                  1|\n|MONROE         |          74.10|                 1,299|                       17.73|         100.00%|                 1|                  1|\n|BRADFORD       |          72.03|                 5,466|                       16.68|         100.00%|                 1|                  1|\n|SULLIVAN       |          71.10|                   918|                       16.93|         100.00%|                 1|                  1|\n|JUNIATA        |          67.81|                 1,782|                       15.92|         100.00%|                 1|                  1|\n|HUNTINGDON     |          51.77|                 2,558|                       14.15|           0.00%|                 1|                  0|\n|CLEARFIELD     |          48.54|                13,056|                       11.37|          25.00%|                 4|                  1|\n|DAUPHIN        |          44.11|                 8,410|                        9.96|          50.00%|                 2|                  1|\n|NORTHUMBERLAND |          43.73|                 9,087|                       11.17|           0.00%|                 4|                  0|\n|POTTER         |          41.26|                 9,062|                        9.55|          33.33%|                 3|                  1|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_county_plot <- st_transform(agg_county, crs = 26917)     # NAD83 / UTM zone 17N\npa_hospitals_plot <- st_transform(pa_hos_proj, crs = st_crs(pa_county_plot))\n\n\nggplot() +\n  geom_sf(\n    data = pa_county_plot,\n    aes(fill = pct_vul_underserved),\n    color = \"white\",\n    size = 0.2\n  ) +\n  \n  #Hospital points\n  geom_sf(\n    data = pa_hospitals_plot,\n    aes(shape = \"Hospital\"),  \n    color=\"orange\",\n    size = 1.5,\n    stroke = 0.4\n  ) +\n  \n  scale_fill_gradientn(\n    colors = c(\"grey92\", \"#6baed6\", \"#08306b\"),\n    name = \"% Vulnerable Tracts\\nUnderserved\",\n    labels = label_percent(scale = 1, accuracy = 1)\n  ) +\n  \n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Counties shaded by share of vulnerable tracts that are underserved\",\n    caption = \"Source: ACS & Healthcare Facility Data\"\n  ) +\n  \n  theme_void(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, margin = margin(b = 5)),\n    plot.caption = element_text(size = 9, color = \"gray30\"),\n    legend.title = element_text(size = 11, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_tracts <- st_transform(pa_tracts, crs=26917)\nvul_center <- st_transform(vul_center, crs=26917)\nvul_tracts_poly <- st_join(pa_tracts, vul_center, join= st_contains)\n\n# Create detailed tract-level map\nggplot() +\n  geom_sf(\n    data = vul_tracts_poly,\n    aes(fill = as.factor(underserved)),\n    color = \"grey80\",\n    size = 0.5\n  ) +\n  \n  geom_sf(\n    data = pa_hospitals_plot,\n    aes(shape = \"Hospital\", color = \"Hospital\"),  # 👈 通过 aes() 进入图例\n    size = 1.2,\n    stroke = 0.4\n  ) +\n  \n scale_fill_manual(\n    name = \"Underserved Status\",\n    values = c(\"0\" = \"lightcoral\", \"1\" = \"firebrick3\"),  # 👈 定义 0/1/NA 颜色\n    labels = c(\"0\"=\"Vulnerable\", \"1\" = \"Vulnerabale & Underserved\" ),\n )+\n  \n  scale_color_manual(\n    name = \"\",  \n    values = c(\"Hospital\" = \"orange\")\n  ) +\n  scale_shape_manual(\n    name = \"\",\n    values = c(\"Hospital\" = 16)\n  ) +\n  \n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Counties shaded by share of vulnerable tracts that are underserved\",\n    caption = \"Source: ACS & Healthcare Facility Data\"\n  ) +\n  \n  theme_void(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, margin = margin(b = 5)),\n    plot.caption = element_text(size = 9, color = \"gray30\"),\n    legend.title = element_text(size = 11, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nggplot(vul_tracts_poly, aes(x = dist_mi, y = total_pop)) +\n  geom_point(alpha = 0.6, color = \"#FF7F50\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"gray30\") +\n  labs(\n    title = \"Hospital Distance vs. Vulnerable Population Size\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Vulnerable Population (people)\",\n    caption = \"Tracts farther from hospitals tend to have smaller but more isolated vulnerable populations.\"\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nphi_school <- read_csv(\"data_2/PaSchoolDistricts2024_03/2025-2026 Master School List (20251001).csv\")\nphi_crime <- read_csv(\"data_2/PaSchoolDistricts2024_03/incidents_part1_part2.csv\")\nbike <- st_read(\"data_2/PaSchoolDistricts2024_03/Bike_Network.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Bike_Network' from data source \n  `C:\\Users\\12345\\Documents\\GitHub\\portfolio-setup-jyxu48\\Assignments\\assignment_2\\data_2\\PaSchoolDistricts2024_03\\Bike_Network.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5225 features and 8 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: -8378937 ymin: 4847835 xmax: -8345146 ymax: 4883978\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ncity_limit <- st_read(\"data_2/PaSchoolDistricts2024_03/City_Limits.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `City_Limits' from data source \n  `C:\\Users\\12345\\Documents\\GitHub\\portfolio-setup-jyxu48\\Assignments\\assignment_2\\data_2\\PaSchoolDistricts2024_03\\City_Limits.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -75.28031 ymin: 39.86747 xmax: -74.95575 ymax: 40.13793\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nphi_school <- phi_school %>%\n  separate(`GPS Location`, into = c(\"lat\", \"lng\"), sep = \",\") %>%\n  mutate(\n    lat = as.numeric(lat),\n    lng = as.numeric(lng)\n  )\nphi_crime <- phi_crime %>% drop_na(lng, lat)\n\nst_school <- st_as_sf(phi_school, coords = c(\"lng\", \"lat\"), crs = 4326)\nst_crime <- st_as_sf(phi_crime, coords = c(\"lng\", \"lat\"), crs = 4326)\n\ntarget_crs <- 26918\n\nst_school <- st_transform(st_school, crs = target_crs)\nst_crime  <- st_transform(st_crime,  crs = target_crs)\nbike       <- st_transform(bike, crs = target_crs)\ncity_limit <- st_transform(city_limit, crs = target_crs)\n\nggplot() +\n  geom_sf(data = city_limit, fill = \"grey95\", color = \"grey60\", size = 0.4) + \n  geom_sf(data = bike, color = \"#2b83ba\", size = 0.5) +\n  geom_sf(data = st_school, color = \"coral\", shape = 16, size = 1.2) +\n  labs(\n    title = \"Philadelphia Schools, Crime Incidents, and Bike Network\",\n    caption = \"Source: OpenDataPhilly\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-12-1.png){width=3000}\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n\nI choose School List of Philadelphia, Crime Incidents of Philadelphia and Bike Networks.\nI choose these data because it's a question directly related to urban safety and equitable access for students.\n- What is the data source and date?\n\nThe data is from \"opendataphilly.org\" and it is the data of 2025. (date of bike network data is unknown)\n- How many features does it contain?\n\nSchool List contains 1:Administrative info 2:Contact info 3:Location\nCrime Incident contains 1:Time 2:Location 3:Crime category\nBike Networks contains 1:Name 2:road info(type,length,location)\n- What CRS is it in? Did you need to transform it?\n\nThey are all in EPSG:4326 (WGS84).\nYes I need to transform them into another CRS(EPSG:26918) which is more accurate locally.\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\nAre schools located in high-crime areas also underserved by safe biking and walking infrastructure?\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\nst_school <- st_school %>%\n  rename(Publication_Name = `Publication Name`)\nschool_buffers <- st_buffer(st_school, dist = 305)  # 1000 ft ≈ 305 m\n\ncrime_in_buffer <- st_join(st_crime, school_buffers, join = st_within)\n\ncrime_summary <- crime_in_buffer %>%\n  st_drop_geometry() %>%\n  group_by(Publication_Name) %>%\n  summarise(crime_n = n())\n\n# Spatial intersection: calculate total length of bike network inside each buffer\nbike_in_buffer <- st_intersection(bike, school_buffers)\n\nbike_summary <- bike_in_buffer %>%\n  group_by(Publication_Name) %>%\n  summarise(bike_length_m = sum(st_length(geometry))) %>%\n  mutate(bike_length_mi = set_units(bike_length_m, \"mi\"))\n\n# Combine results into a single summary table\nschool_safety <- school_buffers %>%\n  left_join(st_drop_geometry(crime_summary), by = \"Publication_Name\") %>%\n  left_join(st_drop_geometry(bike_summary),  by = \"Publication_Name\") %>%\n  mutate(\n    crime_n = replace_na(crime_n, 0),\n    bike_length_mi = replace_na(as.numeric(bike_length_mi), 0),\n    safety_index = crime_n / (bike_length_mi + 0.1)\n  )\n\n# Summary statistics\nsummary_stats <- school_safety %>%\n  st_drop_geometry() %>%\n  summarise(\n    mean_crime = mean(crime_n),\n    mean_bike = mean(as.numeric(bike_length_mi)),\n    high_crime_schools = sum(crime_n > mean_crime),\n    low_bike_schools = sum(as.numeric(bike_length_mi) < mean_bike)\n  )\n\nprint(summary_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  mean_crime mean_bike high_crime_schools low_bike_schools\n       <dbl>     <dbl>              <int>            <int>\n1       183.     0.430                135              203\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualization: highlight high-crime, low-bike schools\np1 <- ggplot() +\n  geom_sf(data = city_limit, fill = \"grey95\", color = \"grey60\") +\n  geom_sf(data = bike, color = \"grey70\", size = 0.2) +\n  geom_sf(\n    data = school_safety,\n    aes(fill = safety_index),\n    shape = 21, color = \"black\", size = 2\n  ) +\n  scale_fill_gradientn(\n    colors = c(\n      \"#313695\",  \n      \"#74add1\",  \n      \"#e0f3f8\",  \n      \"#fee090\",  \n      \"#f46d43\",  \n      \"#a50026\"   \n    ),\n    name = \"Crime to Bike_length\"\n  ) +\n  \n  labs(\n    title = \"Philadelphia School Safety Zones\",\n    subtitle = \"High values indicate more crime and less bike coverage\",\n  ) +\n  \n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(size = 8),\n    legend.position = \"right\"\n  )\n\np2 <- ggplot() +\n  geom_sf(data = city_limit, fill = \"grey95\", color = \"grey60\") +\n  geom_sf(data = bike, color = \"grey70\", size = 0.4) +\n  geom_sf(\n    data = school_safety,\n    aes(fill = crime_n),\n    shape = 21, color = \"black\", size = 2\n  ) +\n  scale_fill_gradientn(\n    colors = c(\n      \"#313695\",  \n      \"#74add1\",  \n      \"#e0f3f8\",  \n      \"#fee090\",  \n      \"#f46d43\",  \n      \"#a50026\" \n    ),\n    name = \"Crime Incidents\\n(Count)\"\n  ) +\n  labs(\n    title = \"Philadelphia School Safety Zones\",\n    subtitle = \"Crime incidents within 1000ft school safety zones\",\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(size = 8),\n    legend.position = \"right\"\n  )\n\np3 <- ggplot() +\n  geom_sf(data = city_limit, fill = \"grey95\", color = \"grey60\") +\n  geom_sf(data = bike, color = \"grey70\", size = 0.4) +\n  geom_sf(\n    data = school_safety,\n    aes(fill = bike_length_mi),\n    shape = 21, color = \"black\", size = 2\n  ) +\n  scale_fill_gradientn(\n    colors = c(\n      \"#a50026\",\n      \"#f46d43\", \n      \"#fee090\",\n      \"#e0f3f8\", \n      \"#74add1\", \n      \"#313695\"\n    ),\n    name = \"Bike Network\\n(Miles)\"\n  ) +\n  labs(\n    title = \"Philadelphia School Safety Zones\",\n    subtitle = \"Bike infrastructure length within 1000ft school safety zones\",\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 12),\n    plot.subtitle = element_text(size = 8),\n    legend.position = \"right\"\n  )\n\n(p1 | p2 | p3) +\n  plot_annotation(\n    title = \"Philadelphia School Safety Zone Analysis\",\n    caption = \"Data: OpenDataPhilly\"\n  )\n```\n\n::: {.cell-output-display}\n![](Jinyang_Xu_Assignment2_files/figure-html/unnamed-chunk-13-1.png){width=2000}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nThe maps show that high-crime and low-bike-coverage school zones largely overlap in central to northern and Western Philadelphia, indicating a clear spatial correlation between the two. This suggests that areas with more crime tend to have less biking infrastructure, highlighting potential safety and accessibility concerns for students in those neighborhoods.\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\nI deleted some descriptive sentences and symbols so now the Assignment1 looks cleaner.\n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}